#ifndef _GPU_BVH_COMMON_H_
#define _GPU_BVH_COMMON_H_

// MUST be the first include — pulls in the engine-injected
// ENGINE_PREPROCESSORTS_INC block where every [TtShaderDefine] struct
// (FGpuBvhNode / FGpuRay / FGpuHit) is auto-generated. Without this, the
// FGpuBvhNode reference below resolves to "unexpected token" (X3000) and
// the error cascades into "undeclared identifier 'outHitT'" (X3004) in the
// helper body. See CodingGuidelines.md §3.4.
#include "../../../Inc/GlobalDefine.cginc"

// =============================================================================
// GpuBvhCommon.cginc
//
// HLSL-side helper for CSharpCode/Bricks/Collision/BVH/TtGpuBvh.cs.
// Provides the stack-based iterative BVH traversal used by
// GpuBvhTraversal.compute.
//
// IMPORTANT: the three structs (FGpuBvhNode / FGpuRay / FGpuHit) are NOT defined
// here. They are auto-generated by the engine's shader compiler from the C#
// definitions in TtGpuBvh.cs marked with [TtShaderDefine] (see
// Documents/Coding/CodeLib.md §11). Hand-writing them again here would cause
// a HLSL redefinition error — keep the single source of truth on the C# side.
//
// Layout contract (32 bytes per node, AoS, half a 64B cache line):
//   float3 BoxMin;           // 0..12
//   uint   Child1;           // 12..16   == LeafChildSentinel marks a leaf
//   float3 BoxMax;           // 16..28
//   uint   Child2OrPayload;  // 28..32   leaf: dense leafIndex
//                                        internal: index of right child
//
// Sentinel: Child1 == 0xFFFFFFFF means this is a leaf node.
// =============================================================================

#define GPU_BVH_LEAF_SENTINEL  0xFFFFFFFFu
#define GPU_BVH_NULL_PAYLOAD   0xFFFFFFFFu
#define GPU_BVH_STACK_SIZE     64

// Slab test: returns true and writes the entry t into outTEnter if the ray
// (origin + t * dir, t in [0, maxT]) intersects the AABB [boxMin, boxMax].
// outTEnter is clamped to >= 0 for rays starting inside the box.
//
// invDir is precomputed once per ray (1.0 / dir, with safe division for zero
// components) and reused across every node test, mirroring the CPU code in
// TtDynamicBVH.RaySlabIntersect.
bool RayAabbIntersect(float3 boxMin, float3 boxMax,
                      float3 origin, float3 invDir, float maxT,
                      out float outTEnter)
{
    float3 t1 = (boxMin - origin) * invDir;
    float3 t2 = (boxMax - origin) * invDir;

    float3 tmin3 = min(t1, t2);
    float3 tmax3 = max(t1, t2);

    float tEnter = max(max(tmin3.x, tmin3.y), tmin3.z);
    float tExit  = min(min(tmax3.x, tmax3.y), tmax3.z);

    outTEnter = max(tEnter, 0.0f);
    // Allow tangential hits (tEnter == tExit) and rays starting inside the box.
    return tExit >= outTEnter && outTEnter <= maxT;
}

// Compute a numerically-safe inverse direction for slab tests. Replaces
// near-zero components with a large signed value so that
// (boxMin - origin) * invDir.x produces +/-inf instead of NaN.
float3 SafeInvDir(float3 dir)
{
    const float kEps = 1e-20f;
    float3 absDir = max(abs(dir), float3(kEps, kEps, kEps));
    float3 sgn    = float3(dir.x >= 0 ? 1.0f : -1.0f,
                           dir.y >= 0 ? 1.0f : -1.0f,
                           dir.z >= 0 ? 1.0f : -1.0f);
    return sgn / absDir;
}

// -----------------------------------------------------------------------------
// Iterative closest-hit traversal.
//
// Walks the BVH with a thread-local stack and reports the leaf with the
// smallest entry-t along the ray. The semantics match TtDynamicBVH.RayCast
// at "AABB precision" — there's no per-leaf geometry on the GPU side here,
// so a leaf hit is simply ray-vs-leaf-AABB intersection.
//
// Args:
//   nodes        : SRV holding the flattened BVH (root at index 0).
//   nodeCount    : total number of nodes in the buffer (for bounds-check
//                  asserts; runtime kernel doesn't actually need it).
//   rootIndex    : usually 0; passed in case the caller wants to traverse
//                  a sub-tree.
//   ray          : the input ray.
//   outHitT      : closest hit t (== ray.MaxT on miss).
//   outPayload   : leafIndex of the closest hit (== GPU_BVH_NULL_PAYLOAD on miss).
//   outNodeId    : debug-only, GPU node index of the closest hit.
// -----------------------------------------------------------------------------
void TraverseBvhClosest(StructuredBuffer<FGpuBvhNode> nodes,
                        uint nodeCount, uint rootIndex,
                        FGpuRay ray,
                        out float outHitT, out uint outPayload, out uint outNodeId)
{
    outHitT    = ray.MaxT;
    outPayload = GPU_BVH_NULL_PAYLOAD;
    outNodeId  = GPU_BVH_NULL_PAYLOAD;

    if (nodeCount == 0)
        return;

    float3 invDir = SafeInvDir(ray.Dir);

    uint stack[GPU_BVH_STACK_SIZE];
    int  top = 0;
    stack[top++] = rootIndex;

    [loop]
    while (top > 0)
    {
        uint nodeIdx = stack[--top];
        FGpuBvhNode node = nodes[nodeIdx];

        float tEnter;
        if (!RayAabbIntersect(node.BoxMin, node.BoxMax, ray.Origin, invDir, outHitT, tEnter))
            continue;

        // Leaf: record if it's the closest so far. We use the slab tEnter as
        // the hit distance — there's no geometry here, only AABBs.
        if (node.Child1 == GPU_BVH_LEAF_SENTINEL)
        {
            if (tEnter < outHitT)
            {
                outHitT    = tEnter;
                outPayload = node.Child2OrPayload;
                outNodeId  = nodeIdx;
            }
            continue;
        }

        // Internal node: push both children. Stack overflow guard so a
        // pathological tree can't trash adjacent locals.
        if (top + 2 <= GPU_BVH_STACK_SIZE)
        {
            stack[top++] = node.Child1;
            stack[top++] = node.Child2OrPayload;
        }
    }
}

#endif // _GPU_BVH_COMMON_H_
