<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="AssimpNetter" Version="6.0.2.1" />
    <PackageVersion Include="BCnEncoder.Net" Version="2.2.1" />
    <PackageVersion Include="ClangSharp" Version="20.1.2.1" />
    <PackageVersion Include="envdte100" Version="17.14.40260" />
    <PackageVersion Include="libclang.runtime.win-x64" Version="20.1.2" />
    <PackageVersion Include="MemoryInterop.ILPatcher" Version="2.2.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="4.10.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.10.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.10.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.10.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.10.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageVersion Include="Microsoft.VisualStudio.SlnGen" Version="5.3.0" />
    <PackageVersion Include="Mono.Cecil" Version="0.11.6" />
    <PackageVersion Include="MvsSln" Version="2.6.0" />
    <PackageVersion Include="NLua" Version="1.7.6" />
    <PackageVersion Include="NPOI" Version="2.7.2" />
    <PackageVersion Include="ppy.SDL2-CS" Version="1.0.82" />
    <PackageVersion Include="ppy.SDL3-CS" Version="2025.703.0" />
    <PackageVersion Include="RIPEMD160" Version="1.0.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="System.CodeDom" Version="9.0.0" />
    <PackageVersion Include="System.Runtime.Loader" Version="4.3.0" />
    <PackageVersion Include="TencentCloudSDK" Version="3.0.1268" />
  </ItemGroup>
</Project>
