#pragma once
#include "../Base/IUnknown.h"
#include "../Base/thread/vfxcritical.h"
#include "../Base/thread/vfxthread.h"
#include "NxEvent.h"
#include "NxRHIDefine.h"

NS_BEGIN

namespace NxRHI
{
	class IGpuDevice;
	struct FBufferDesc;
	class IBuffer;
	class ICommandList;
	struct FCbvDesc;
	class ICbView;
	struct FVbvDesc;
	class IVbView;
	struct FIbvDesc;
	class IIbView;
	struct FUavDesc;
	class IUaView;
	struct FSrvDesc;
	class ISrView;
	struct FSamplerDesc;
	class ISampler;
	struct FGpuPipelineDesc;
	class IGraphicsEffect;
	class IGpuPipeline;
	class IGpuDrawState;
	struct FInputLayoutDesc;
	class IInputLayout;
	struct FShaderDesc;
	class IShader;
	struct FFenceDesc;
	class IFence;
	struct FEventDesc;
	class IEvent;
	class IGraphicDraw;
	class IComputeDraw;
	class IRayTracingDraw;
	class ICopyDraw;
	class IActionDraw;
	struct FTextureDesc;
	class ITexture;
	class IGpuResource;
	struct FRtvDesc;
	class IRenderTargetView;
	struct FDsvDesc;
	class IDepthStencilView;
	struct FSwapChainDesc;
	class ISwapChain;
	struct FRenderPassDesc;
	class IRenderPass;
	class IFrameBuffers;
	struct FGpuDeviceDesc;
	class IGpuDevice;
	class FGpuPipelineManager;
	class ICmdQueue;
	class IComputeEffect;
	class IRayTracingEffect;
	class IGpuBufferData;
	class IGpuScope;
	class FVertexArray;
	class FGeomMesh;
	struct FAccelerationStructureDesc;
	class IAccelerationStructure;
	struct FAStructureInstanceDesc;
	class IAStructureInstance;
	struct FTopAccelerationStructureDesc;
	class ITopAccelerationStructure;

	enum TR_ENUM(SV_EnumNoFlags)
		ERhiType
	{
		RHI_D3D11,
			RHI_D3D12,
			RHI_VK,
			RHI_GL,
			RHI_Metal,
			RHI_VirtualDevice,
	};
	struct TR_CLASS(SV_LayoutStruct = 8)
		FGpuSystemDesc
	{
		vBOOL		UseRenderDoc = TRUE;
		vBOOL		CreateDebugLayer = FALSE;
		vBOOL		GpuBaseValidation = FALSE;
		void*		WindowHandle = nullptr;
		VNameString	RenderDocPath;
	};

	enum TR_ENUM(SV_EnumNoFlags)
		EDx12MessageId{
		UNKNOWN = 0,
		STRING_FROM_APPLICATION = 1,
		CORRUPTED_THIS = 2,
		CORRUPTED_PARAMETER1 = 3,
		CORRUPTED_PARAMETER2 = 4,
		CORRUPTED_PARAMETER3 = 5,
		CORRUPTED_PARAMETER4 = 6,
		CORRUPTED_PARAMETER5 = 7,
		CORRUPTED_PARAMETER6 = 8,
		CORRUPTED_PARAMETER7 = 9,
		CORRUPTED_PARAMETER8 = 10,
		CORRUPTED_PARAMETER9 = 11,
		CORRUPTED_PARAMETER10 = 12,
		CORRUPTED_PARAMETER11 = 13,
		CORRUPTED_PARAMETER12 = 14,
		CORRUPTED_PARAMETER13 = 15,
		CORRUPTED_PARAMETER14 = 16,
		CORRUPTED_PARAMETER15 = 17,
		CORRUPTED_MULTITHREADING = 18,
		MESSAGE_REPORTING_OUTOFMEMORY = 19,
		GETPRIVATEDATA_MOREDATA = 20,
		SETPRIVATEDATA_INVALIDFREEDATA = 21,
		SETPRIVATEDATA_CHANGINGPARAMS = 24,
		SETPRIVATEDATA_OUTOFMEMORY = 25,
		CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT = 26,
		CREATESHADERRESOURCEVIEW_INVALIDDESC = 27,
		CREATESHADERRESOURCEVIEW_INVALIDFORMAT = 28,
		CREATESHADERRESOURCEVIEW_INVALIDVIDEOPLANESLICE = 29,
		CREATESHADERRESOURCEVIEW_INVALIDPLANESLICE = 30,
		CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS = 31,
		CREATESHADERRESOURCEVIEW_INVALIDRESOURCE = 32,
		CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT = 35,
		CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT = 36,
		CREATERENDERTARGETVIEW_INVALIDDESC = 37,
		CREATERENDERTARGETVIEW_INVALIDFORMAT = 38,
		CREATERENDERTARGETVIEW_INVALIDVIDEOPLANESLICE = 39,
		CREATERENDERTARGETVIEW_INVALIDPLANESLICE = 40,
		CREATERENDERTARGETVIEW_INVALIDDIMENSIONS = 41,
		CREATERENDERTARGETVIEW_INVALIDRESOURCE = 42,
		CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT = 45,
		CREATEDEPTHSTENCILVIEW_INVALIDDESC = 46,
		CREATEDEPTHSTENCILVIEW_INVALIDFORMAT = 47,
		CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS = 48,
		CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE = 49,
		CREATEINPUTLAYOUT_OUTOFMEMORY = 52,
		CREATEINPUTLAYOUT_TOOMANYELEMENTS = 53,
		CREATEINPUTLAYOUT_INVALIDFORMAT = 54,
		CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT = 55,
		CREATEINPUTLAYOUT_INVALIDSLOT = 56,
		CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS = 57,
		CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH = 58,
		CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE = 59,
		CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE = 60,
		CREATEINPUTLAYOUT_INVALIDALIGNMENT = 61,
		CREATEINPUTLAYOUT_DUPLICATESEMANTIC = 62,
		CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE = 63,
		CREATEINPUTLAYOUT_NULLSEMANTIC = 64,
		CREATEINPUTLAYOUT_MISSINGELEMENT = 65,
		CREATEVERTEXSHADER_OUTOFMEMORY = 66,
		CREATEVERTEXSHADER_INVALIDSHADERBYTECODE = 67,
		CREATEVERTEXSHADER_INVALIDSHADERTYPE = 68,
		CREATEGEOMETRYSHADER_OUTOFMEMORY = 69,
		CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE = 70,
		CREATEGEOMETRYSHADER_INVALIDSHADERTYPE = 71,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY = 72,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE = 73,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE = 74,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES = 75,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED = 76,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED = 79,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT = 80,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT = 81,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT = 82,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT = 83,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION = 84,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT = 85,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE = 86,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC = 87,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH = 88,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS = 89,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX = 90,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE = 91,
		CREATEPIXELSHADER_OUTOFMEMORY = 92,
		CREATEPIXELSHADER_INVALIDSHADERBYTECODE = 93,
		CREATEPIXELSHADER_INVALIDSHADERTYPE = 94,
		CREATERASTERIZERSTATE_INVALIDFILLMODE = 95,
		CREATERASTERIZERSTATE_INVALIDCULLMODE = 96,
		CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP = 97,
		CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS = 98,
		CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK = 100,
		CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC = 101,
		CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP = 102,
		CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP = 103,
		CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP = 104,
		CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC = 105,
		CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP = 106,
		CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP = 107,
		CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP = 108,
		CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC = 109,
		CREATEBLENDSTATE_INVALIDSRCBLEND = 111,
		CREATEBLENDSTATE_INVALIDDESTBLEND = 112,
		CREATEBLENDSTATE_INVALIDBLENDOP = 113,
		CREATEBLENDSTATE_INVALIDSRCBLENDALPHA = 114,
		CREATEBLENDSTATE_INVALIDDESTBLENDALPHA = 115,
		CREATEBLENDSTATE_INVALIDBLENDOPALPHA = 116,
		CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK = 117,
		GET_PROGRAM_IDENTIFIER_ERROR,
		GET_WORK_GRAPH_PROPERTIES_ERROR,
		SET_PROGRAM_ERROR,
		CLEARDEPTHSTENCILVIEW_INVALID = 135,
		COMMAND_LIST_DRAW_ROOT_SIGNATURE_NOT_SET = 200,
		COMMAND_LIST_DRAW_ROOT_SIGNATURE_MISMATCH = 201,
		COMMAND_LIST_DRAW_VERTEX_BUFFER_NOT_SET = 202,
		COMMAND_LIST_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL = 209,
		COMMAND_LIST_DRAW_VERTEX_BUFFER_TOO_SMALL = 210,
		COMMAND_LIST_DRAW_INDEX_BUFFER_NOT_SET = 211,
		COMMAND_LIST_DRAW_INDEX_BUFFER_FORMAT_INVALID = 212,
		COMMAND_LIST_DRAW_INDEX_BUFFER_TOO_SMALL = 213,
		COMMAND_LIST_DRAW_INVALID_PRIMITIVETOPOLOGY = 219,
		COMMAND_LIST_DRAW_VERTEX_STRIDE_UNALIGNED = 221,
		COMMAND_LIST_DRAW_INDEX_OFFSET_UNALIGNED = 222,
		DEVICE_REMOVAL_PROCESS_AT_FAULT = 232,
		DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT = 233,
		DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT = 234,
		CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC = 239,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC = 240,
		CREATEINPUTLAYOUT_TYPE_MISMATCH = 245,
		CREATEINPUTLAYOUT_EMPTY_LAYOUT = 253,
		LIVE_OBJECT_SUMMARY = 255,
		LIVE_DEVICE = 274,
		LIVE_SWAPCHAIN = 275,
		CREATEDEPTHSTENCILVIEW_INVALIDFLAGS = 276,
		CREATEVERTEXSHADER_INVALIDCLASSLINKAGE = 277,
		CREATEGEOMETRYSHADER_INVALIDCLASSLINKAGE = 278,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAMTORASTERIZER = 280,
		CREATEPIXELSHADER_INVALIDCLASSLINKAGE = 283,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTREAM = 284,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDENTRIES = 285,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDSTRIDES = 286,
		CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMSTRIDES = 287,
		CREATEHULLSHADER_OUTOFMEMORY = 289,
		CREATEHULLSHADER_INVALIDSHADERBYTECODE = 290,
		CREATEHULLSHADER_INVALIDSHADERTYPE = 291,
		CREATEHULLSHADER_INVALIDCLASSLINKAGE = 292,
		CREATEDOMAINSHADER_OUTOFMEMORY = 294,
		CREATEDOMAINSHADER_INVALIDSHADERBYTECODE = 295,
		CREATEDOMAINSHADER_INVALIDSHADERTYPE = 296,
		CREATEDOMAINSHADER_INVALIDCLASSLINKAGE = 297,
		RESOURCE_UNMAP_NOTMAPPED = 310,
		DEVICE_CHECKFEATURESUPPORT_MISMATCHED_DATA_SIZE = 318,
		CREATECOMPUTESHADER_OUTOFMEMORY = 321,
		CREATECOMPUTESHADER_INVALIDSHADERBYTECODE = 322,
		CREATECOMPUTESHADER_INVALIDCLASSLINKAGE = 323,
		DEVICE_CREATEVERTEXSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 331,
		DEVICE_CREATEHULLSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 332,
		DEVICE_CREATEDOMAINSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 333,
		DEVICE_CREATEGEOMETRYSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 334,
		DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEFLOATOPSNOTSUPPORTED = 335,
		DEVICE_CREATEPIXELSHADER_DOUBLEFLOATOPSNOTSUPPORTED = 336,
		DEVICE_CREATECOMPUTESHADER_DOUBLEFLOATOPSNOTSUPPORTED = 337,
		CREATEUNORDEREDACCESSVIEW_INVALIDRESOURCE = 340,
		CREATEUNORDEREDACCESSVIEW_INVALIDDESC = 341,
		CREATEUNORDEREDACCESSVIEW_INVALIDFORMAT = 342,
		CREATEUNORDEREDACCESSVIEW_INVALIDVIDEOPLANESLICE = 343,
		CREATEUNORDEREDACCESSVIEW_INVALIDPLANESLICE = 344,
		CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS = 345,
		CREATEUNORDEREDACCESSVIEW_UNRECOGNIZEDFORMAT = 346,
		CREATEUNORDEREDACCESSVIEW_INVALIDFLAGS = 354,
		CREATERASTERIZERSTATE_INVALIDFORCEDSAMPLECOUNT = 401,
		CREATEBLENDSTATE_INVALIDLOGICOPS = 403,
		DEVICE_CREATEVERTEXSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 410,
		DEVICE_CREATEHULLSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 412,
		DEVICE_CREATEDOMAINSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 414,
		DEVICE_CREATEGEOMETRYSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 416,
		DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DOUBLEEXTENSIONSNOTSUPPORTED = 418,
		DEVICE_CREATEPIXELSHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 420,
		DEVICE_CREATECOMPUTESHADER_DOUBLEEXTENSIONSNOTSUPPORTED = 422,
		DEVICE_CREATEVERTEXSHADER_UAVSNOTSUPPORTED = 425,
		DEVICE_CREATEHULLSHADER_UAVSNOTSUPPORTED = 426,
		DEVICE_CREATEDOMAINSHADER_UAVSNOTSUPPORTED = 427,
		DEVICE_CREATEGEOMETRYSHADER_UAVSNOTSUPPORTED = 428,
		DEVICE_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UAVSNOTSUPPORTED = 429,
		DEVICE_CREATEPIXELSHADER_UAVSNOTSUPPORTED = 430,
		DEVICE_CREATECOMPUTESHADER_UAVSNOTSUPPORTED = 431,
		DEVICE_CLEARVIEW_INVALIDSOURCERECT = 447,
		DEVICE_CLEARVIEW_EMPTYRECT = 448,
		UPDATETILEMAPPINGS_INVALID_PARAMETER = 493,
		COPYTILEMAPPINGS_INVALID_PARAMETER = 494,
		CREATEDEVICE_INVALIDARGS = 506,
		CREATEDEVICE_WARNING = 507,
		RESOURCE_BARRIER_INVALID_TYPE = 519,
		RESOURCE_BARRIER_NULL_POINTER = 520,
		RESOURCE_BARRIER_INVALID_SUBRESOURCE = 521,
		RESOURCE_BARRIER_RESERVED_BITS = 522,
		RESOURCE_BARRIER_MISSING_BIND_FLAGS = 523,
		RESOURCE_BARRIER_MISMATCHING_MISC_FLAGS = 524,
		RESOURCE_BARRIER_MATCHING_STATES = 525,
		RESOURCE_BARRIER_INVALID_COMBINATION = 526,
		RESOURCE_BARRIER_BEFORE_AFTER_MISMATCH = 527,
		RESOURCE_BARRIER_INVALID_RESOURCE = 528,
		RESOURCE_BARRIER_SAMPLE_COUNT = 529,
		RESOURCE_BARRIER_INVALID_FLAGS = 530,
		RESOURCE_BARRIER_INVALID_COMBINED_FLAGS = 531,
		RESOURCE_BARRIER_INVALID_FLAGS_FOR_FORMAT = 532,
		RESOURCE_BARRIER_INVALID_SPLIT_BARRIER = 533,
		RESOURCE_BARRIER_UNMATCHED_END = 534,
		RESOURCE_BARRIER_UNMATCHED_BEGIN = 535,
		RESOURCE_BARRIER_INVALID_FLAG = 536,
		RESOURCE_BARRIER_INVALID_COMMAND_LIST_TYPE = 537,
		INVALID_SUBRESOURCE_STATE = 538,
		COMMAND_ALLOCATOR_CONTENTION = 540,
		COMMAND_ALLOCATOR_RESET = 541,
		COMMAND_ALLOCATOR_RESET_BUNDLE = 542,
		COMMAND_ALLOCATOR_CANNOT_RESET = 543,
		COMMAND_LIST_OPEN = 544,
		INVALID_BUNDLE_API = 546,
		COMMAND_LIST_CLOSED = 547,
		WRONG_COMMAND_ALLOCATOR_TYPE = 549,
		COMMAND_ALLOCATOR_SYNC = 552,
		COMMAND_LIST_SYNC = 553,
		SET_DESCRIPTOR_HEAP_INVALID = 554,
		CREATE_COMMANDQUEUE = 557,
		CREATE_COMMANDALLOCATOR = 558,
		CREATE_PIPELINESTATE = 559,
		CREATE_COMMANDLIST12 = 560,
		CREATE_RESOURCE = 562,
		CREATE_DESCRIPTORHEAP = 563,
		CREATE_ROOTSIGNATURE = 564,
		CREATE_LIBRARY = 565,
		CREATE_HEAP = 566,
		CREATE_MONITOREDFENCE = 567,
		CREATE_QUERYHEAP = 568,
		CREATE_COMMANDSIGNATURE = 569,
		LIVE_COMMANDQUEUE = 570,
		LIVE_COMMANDALLOCATOR = 571,
		LIVE_PIPELINESTATE = 572,
		LIVE_COMMANDLIST12 = 573,
		LIVE_RESOURCE = 575,
		LIVE_DESCRIPTORHEAP = 576,
		LIVE_ROOTSIGNATURE = 577,
		LIVE_LIBRARY = 578,
		LIVE_HEAP = 579,
		LIVE_MONITOREDFENCE = 580,
		LIVE_QUERYHEAP = 581,
		LIVE_COMMANDSIGNATURE = 582,
		DESTROY_COMMANDQUEUE = 583,
		DESTROY_COMMANDALLOCATOR = 584,
		DESTROY_PIPELINESTATE = 585,
		DESTROY_COMMANDLIST12 = 586,
		DESTROY_RESOURCE = 588,
		DESTROY_DESCRIPTORHEAP = 589,
		DESTROY_ROOTSIGNATURE = 590,
		DESTROY_LIBRARY = 591,
		DESTROY_HEAP = 592,
		DESTROY_MONITOREDFENCE = 593,
		DESTROY_QUERYHEAP = 594,
		DESTROY_COMMANDSIGNATURE = 595,
		CREATERESOURCE_INVALIDDIMENSIONS = 597,
		CREATERESOURCE_INVALIDMISCFLAGS = 599,
		CREATERESOURCE_INVALIDARG_RETURN = 602,
		CREATERESOURCE_OUTOFMEMORY_RETURN = 603,
		CREATERESOURCE_INVALIDDESC = 604,
		POSSIBLY_INVALID_SUBRESOURCE_STATE = 607,
		INVALID_USE_OF_NON_RESIDENT_RESOURCE = 608,
		POSSIBLE_INVALID_USE_OF_NON_RESIDENT_RESOURCE = 609,
		BUNDLE_PIPELINE_STATE_MISMATCH = 610,
		PRIMITIVE_TOPOLOGY_MISMATCH_PIPELINE_STATE = 611,
		RENDER_TARGET_FORMAT_MISMATCH_PIPELINE_STATE = 613,
		RENDER_TARGET_SAMPLE_DESC_MISMATCH_PIPELINE_STATE = 614,
		DEPTH_STENCIL_FORMAT_MISMATCH_PIPELINE_STATE = 615,
		DEPTH_STENCIL_SAMPLE_DESC_MISMATCH_PIPELINE_STATE = 616,
		CREATESHADER_INVALIDBYTECODE = 622,
		CREATEHEAP_NULLDESC = 623,
		CREATEHEAP_INVALIDSIZE = 624,
		CREATEHEAP_UNRECOGNIZEDHEAPTYPE = 625,
		CREATEHEAP_UNRECOGNIZEDCPUPAGEPROPERTIES = 626,
		CREATEHEAP_UNRECOGNIZEDMEMORYPOOL = 627,
		CREATEHEAP_INVALIDPROPERTIES = 628,
		CREATEHEAP_INVALIDALIGNMENT = 629,
		CREATEHEAP_UNRECOGNIZEDMISCFLAGS = 630,
		CREATEHEAP_INVALIDMISCFLAGS = 631,
		CREATEHEAP_INVALIDARG_RETURN = 632,
		CREATEHEAP_OUTOFMEMORY_RETURN = 633,
		CREATERESOURCEANDHEAP_NULLHEAPPROPERTIES = 634,
		CREATERESOURCEANDHEAP_UNRECOGNIZEDHEAPTYPE = 635,
		CREATERESOURCEANDHEAP_UNRECOGNIZEDCPUPAGEPROPERTIES = 636,
		CREATERESOURCEANDHEAP_UNRECOGNIZEDMEMORYPOOL = 637,
		CREATERESOURCEANDHEAP_INVALIDHEAPPROPERTIES = 638,
		CREATERESOURCEANDHEAP_UNRECOGNIZEDHEAPMISCFLAGS = 639,
		CREATERESOURCEANDHEAP_INVALIDHEAPMISCFLAGS = 640,
		CREATERESOURCEANDHEAP_INVALIDARG_RETURN = 641,
		CREATERESOURCEANDHEAP_OUTOFMEMORY_RETURN = 642,
		GETCUSTOMHEAPPROPERTIES_UNRECOGNIZEDHEAPTYPE = 643,
		GETCUSTOMHEAPPROPERTIES_INVALIDHEAPTYPE = 644,
		CREATE_DESCRIPTOR_HEAP_INVALID_DESC = 645,
		INVALID_DESCRIPTOR_HANDLE = 646,
		CREATERASTERIZERSTATE_INVALID_CONSERVATIVERASTERMODE = 647,
		CREATE_CONSTANT_BUFFER_VIEW_INVALID_RESOURCE = 649,
		CREATE_CONSTANT_BUFFER_VIEW_INVALID_DESC = 650,
		CREATE_UNORDEREDACCESS_VIEW_INVALID_COUNTER_USAGE = 652,
		COPY_DESCRIPTORS_INVALID_RANGES = 653,
		COPY_DESCRIPTORS_WRITE_ONLY_DESCRIPTOR = 654,
		CREATEGRAPHICSPIPELINESTATE_RTV_FORMAT_NOT_UNKNOWN = 655,
		CREATEGRAPHICSPIPELINESTATE_INVALID_RENDER_TARGET_COUNT = 656,
		CREATEGRAPHICSPIPELINESTATE_VERTEX_SHADER_NOT_SET = 657,
		CREATEGRAPHICSPIPELINESTATE_INPUTLAYOUT_NOT_SET = 658,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_HS_DS_SIGNATURE_MISMATCH = 659,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERINDEX = 660,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_COMPONENTTYPE = 661,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_REGISTERMASK = 662,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SYSTEMVALUE = 663,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS = 664,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_MINPRECISION = 665,
		CREATEGRAPHICSPIPELINESTATE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND = 666,
		CREATEGRAPHICSPIPELINESTATE_HS_XOR_DS_MISMATCH = 667,
		CREATEGRAPHICSPIPELINESTATE_HULL_SHADER_INPUT_TOPOLOGY_MISMATCH = 668,
		CREATEGRAPHICSPIPELINESTATE_HS_DS_CONTROL_POINT_COUNT_MISMATCH = 669,
		CREATEGRAPHICSPIPELINESTATE_HS_DS_TESSELLATOR_DOMAIN_MISMATCH = 670,
		CREATEGRAPHICSPIPELINESTATE_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN = 671,
		CREATEGRAPHICSPIPELINESTATE_INVALID_USE_OF_FORCED_SAMPLE_COUNT = 672,
		CREATEGRAPHICSPIPELINESTATE_INVALID_PRIMITIVETOPOLOGY = 673,
		CREATEGRAPHICSPIPELINESTATE_INVALID_SYSTEMVALUE = 674,
		CREATEGRAPHICSPIPELINESTATE_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0 = 675,
		CREATEGRAPHICSPIPELINESTATE_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING = 676,
		CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_TYPE_MISMATCH = 677,
		CREATEGRAPHICSPIPELINESTATE_OM_RENDER_TARGET_DOES_NOT_SUPPORT_LOGIC_OPS = 678,
		CREATEGRAPHICSPIPELINESTATE_RENDERTARGETVIEW_NOT_SET = 679,
		CREATEGRAPHICSPIPELINESTATE_DEPTHSTENCILVIEW_NOT_SET = 680,
		CREATEGRAPHICSPIPELINESTATE_GS_INPUT_PRIMITIVE_MISMATCH = 681,
		CREATEGRAPHICSPIPELINESTATE_POSITION_NOT_PRESENT = 682,
		CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE_FLAGS = 683,
		CREATEGRAPHICSPIPELINESTATE_INVALID_INDEX_BUFFER_PROPERTIES = 684,
		CREATEGRAPHICSPIPELINESTATE_INVALID_SAMPLE_DESC = 685,
		CREATEGRAPHICSPIPELINESTATE_HS_ROOT_SIGNATURE_MISMATCH = 686,
		CREATEGRAPHICSPIPELINESTATE_DS_ROOT_SIGNATURE_MISMATCH = 687,
		CREATEGRAPHICSPIPELINESTATE_VS_ROOT_SIGNATURE_MISMATCH = 688,
		CREATEGRAPHICSPIPELINESTATE_GS_ROOT_SIGNATURE_MISMATCH = 689,
		CREATEGRAPHICSPIPELINESTATE_PS_ROOT_SIGNATURE_MISMATCH = 690,
		CREATEGRAPHICSPIPELINESTATE_MISSING_ROOT_SIGNATURE = 691,
		EXECUTE_BUNDLE_OPEN_BUNDLE = 692,
		EXECUTE_BUNDLE_DESCRIPTOR_HEAP_MISMATCH = 693,
		EXECUTE_BUNDLE_TYPE = 694,
		DRAW_EMPTY_SCISSOR_RECTANGLE = 695,
		CREATE_ROOT_SIGNATURE_BLOB_NOT_FOUND = 696,
		CREATE_ROOT_SIGNATURE_DESERIALIZE_FAILED = 697,
		CREATE_ROOT_SIGNATURE_INVALID_CONFIGURATION = 698,
		CREATE_ROOT_SIGNATURE_NOT_SUPPORTED_ON_DEVICE = 699,
		CREATERESOURCEANDHEAP_NULLRESOURCEPROPERTIES = 700,
		CREATERESOURCEANDHEAP_NULLHEAP = 701,
		GETRESOURCEALLOCATIONINFO_INVALIDRDESCS = 702,
		MAKERESIDENT_NULLOBJECTARRAY = 703,
		EVICT_NULLOBJECTARRAY = 705,
		SET_DESCRIPTOR_TABLE_INVALID = 708,
		SET_ROOT_CONSTANT_INVALID = 709,
		SET_ROOT_CONSTANT_BUFFER_VIEW_INVALID = 710,
		SET_ROOT_SHADER_RESOURCE_VIEW_INVALID = 711,
		SET_ROOT_UNORDERED_ACCESS_VIEW_INVALID = 712,
		SET_VERTEX_BUFFERS_INVALID_DESC = 713,
		SET_INDEX_BUFFER_INVALID_DESC = 715,
		SET_STREAM_OUTPUT_BUFFERS_INVALID_DESC = 717,
		CREATERESOURCE_UNRECOGNIZEDDIMENSIONALITY = 718,
		CREATERESOURCE_UNRECOGNIZEDLAYOUT = 719,
		CREATERESOURCE_INVALIDDIMENSIONALITY = 720,
		CREATERESOURCE_INVALIDALIGNMENT = 721,
		CREATERESOURCE_INVALIDMIPLEVELS = 722,
		CREATERESOURCE_INVALIDSAMPLEDESC = 723,
		CREATERESOURCE_INVALIDLAYOUT = 724,
		SET_INDEX_BUFFER_INVALID = 725,
		SET_VERTEX_BUFFERS_INVALID = 726,
		SET_STREAM_OUTPUT_BUFFERS_INVALID = 727,
		SET_RENDER_TARGETS_INVALID = 728,
		CREATEQUERY_HEAP_INVALID_PARAMETERS = 729,
		BEGIN_END_QUERY_INVALID_PARAMETERS = 731,
		CLOSE_COMMAND_LIST_OPEN_QUERY = 732,
		RESOLVE_QUERY_DATA_INVALID_PARAMETERS = 733,
		SET_PREDICATION_INVALID_PARAMETERS = 734,
		TIMESTAMPS_NOT_SUPPORTED = 735,
		CREATERESOURCE_UNRECOGNIZEDFORMAT = 737,
		CREATERESOURCE_INVALIDFORMAT = 738,
		GETCOPYABLEFOOTPRINTS_INVALIDSUBRESOURCERANGE = 739,
		GETCOPYABLEFOOTPRINTS_INVALIDBASEOFFSET = 740,
		GETCOPYABLELAYOUT_INVALIDSUBRESOURCERANGE = 739,
		GETCOPYABLELAYOUT_INVALIDBASEOFFSET = 740,
		RESOURCE_BARRIER_INVALID_HEAP = 741,
		CREATE_SAMPLER_INVALID = 742,
		CREATECOMMANDSIGNATURE_INVALID = 743,
		EXECUTE_INDIRECT_INVALID_PARAMETERS = 744,
		GETGPUVIRTUALADDRESS_INVALID_RESOURCE_DIMENSION = 745,
		CREATERESOURCE_INVALIDCLEARVALUE = 815,
		CREATERESOURCE_UNRECOGNIZEDCLEARVALUEFORMAT = 816,
		CREATERESOURCE_INVALIDCLEARVALUEFORMAT = 817,
		CREATERESOURCE_CLEARVALUEDENORMFLUSH = 818,
		CLEARRENDERTARGETVIEW_MISMATCHINGCLEARVALUE = 820,
		CLEARDEPTHSTENCILVIEW_MISMATCHINGCLEARVALUE = 821,
		MAP_INVALIDHEAP = 822,
		UNMAP_INVALIDHEAP = 823,
		MAP_INVALIDRESOURCE = 824,
		UNMAP_INVALIDRESOURCE = 825,
		MAP_INVALIDSUBRESOURCE = 826,
		UNMAP_INVALIDSUBRESOURCE = 827,
		MAP_INVALIDRANGE = 828,
		UNMAP_INVALIDRANGE = 829,
		MAP_INVALIDDATAPOINTER = 832,
		MAP_INVALIDARG_RETURN = 833,
		MAP_OUTOFMEMORY_RETURN = 834,
		EXECUTECOMMANDLISTS_BUNDLENOTSUPPORTED = 835,
		EXECUTECOMMANDLISTS_COMMANDLISTMISMATCH = 836,
		EXECUTECOMMANDLISTS_OPENCOMMANDLIST = 837,
		EXECUTECOMMANDLISTS_FAILEDCOMMANDLIST = 838,
		COPYBUFFERREGION_NULLDST = 839,
		COPYBUFFERREGION_INVALIDDSTRESOURCEDIMENSION = 840,
		COPYBUFFERREGION_DSTRANGEOUTOFBOUNDS = 841,
		COPYBUFFERREGION_NULLSRC = 842,
		COPYBUFFERREGION_INVALIDSRCRESOURCEDIMENSION = 843,
		COPYBUFFERREGION_SRCRANGEOUTOFBOUNDS = 844,
		COPYBUFFERREGION_INVALIDCOPYFLAGS = 845,
		COPYTEXTUREREGION_NULLDST = 846,
		COPYTEXTUREREGION_UNRECOGNIZEDDSTTYPE = 847,
		COPYTEXTUREREGION_INVALIDDSTRESOURCEDIMENSION = 848,
		COPYTEXTUREREGION_INVALIDDSTRESOURCE = 849,
		COPYTEXTUREREGION_INVALIDDSTSUBRESOURCE = 850,
		COPYTEXTUREREGION_INVALIDDSTOFFSET = 851,
		COPYTEXTUREREGION_UNRECOGNIZEDDSTFORMAT = 852,
		COPYTEXTUREREGION_INVALIDDSTFORMAT = 853,
		COPYTEXTUREREGION_INVALIDDSTDIMENSIONS = 854,
		COPYTEXTUREREGION_INVALIDDSTROWPITCH = 855,
		COPYTEXTUREREGION_INVALIDDSTPLACEMENT = 856,
		COPYTEXTUREREGION_INVALIDDSTDSPLACEDFOOTPRINTFORMAT = 857,
		COPYTEXTUREREGION_DSTREGIONOUTOFBOUNDS = 858,
		COPYTEXTUREREGION_NULLSRC = 859,
		COPYTEXTUREREGION_UNRECOGNIZEDSRCTYPE = 860,
		COPYTEXTUREREGION_INVALIDSRCRESOURCEDIMENSION = 861,
		COPYTEXTUREREGION_INVALIDSRCRESOURCE = 862,
		COPYTEXTUREREGION_INVALIDSRCSUBRESOURCE = 863,
		COPYTEXTUREREGION_INVALIDSRCOFFSET = 864,
		COPYTEXTUREREGION_UNRECOGNIZEDSRCFORMAT = 865,
		COPYTEXTUREREGION_INVALIDSRCFORMAT = 866,
		COPYTEXTUREREGION_INVALIDSRCDIMENSIONS = 867,
		COPYTEXTUREREGION_INVALIDSRCROWPITCH = 868,
		COPYTEXTUREREGION_INVALIDSRCPLACEMENT = 869,
		COPYTEXTUREREGION_INVALIDSRCDSPLACEDFOOTPRINTFORMAT = 870,
		COPYTEXTUREREGION_SRCREGIONOUTOFBOUNDS = 871,
		COPYTEXTUREREGION_INVALIDDSTCOORDINATES = 872,
		COPYTEXTUREREGION_INVALIDSRCBOX = 873,
		COPYTEXTUREREGION_FORMATMISMATCH = 874,
		COPYTEXTUREREGION_EMPTYBOX = 875,
		COPYTEXTUREREGION_INVALIDCOPYFLAGS = 876,
		RESOLVESUBRESOURCE_INVALID_SUBRESOURCE_INDEX = 877,
		RESOLVESUBRESOURCE_INVALID_FORMAT = 878,
		RESOLVESUBRESOURCE_RESOURCE_MISMATCH = 879,
		RESOLVESUBRESOURCE_INVALID_SAMPLE_COUNT = 880,
		CREATECOMPUTEPIPELINESTATE_INVALID_SHADER = 881,
		CREATECOMPUTEPIPELINESTATE_CS_ROOT_SIGNATURE_MISMATCH = 882,
		CREATECOMPUTEPIPELINESTATE_MISSING_ROOT_SIGNATURE = 883,
		CREATEPIPELINESTATE_INVALIDCACHEDBLOB = 884,
		CREATEPIPELINESTATE_CACHEDBLOBADAPTERMISMATCH = 885,
		CREATEPIPELINESTATE_CACHEDBLOBDRIVERVERSIONMISMATCH = 886,
		CREATEPIPELINESTATE_CACHEDBLOBDESCMISMATCH = 887,
		CREATEPIPELINESTATE_CACHEDBLOBIGNORED = 888,
		WRITETOSUBRESOURCE_INVALIDHEAP = 889,
		WRITETOSUBRESOURCE_INVALIDRESOURCE = 890,
		WRITETOSUBRESOURCE_INVALIDBOX = 891,
		WRITETOSUBRESOURCE_INVALIDSUBRESOURCE = 892,
		WRITETOSUBRESOURCE_EMPTYBOX = 893,
		READFROMSUBRESOURCE_INVALIDHEAP = 894,
		READFROMSUBRESOURCE_INVALIDRESOURCE = 895,
		READFROMSUBRESOURCE_INVALIDBOX = 896,
		READFROMSUBRESOURCE_INVALIDSUBRESOURCE = 897,
		READFROMSUBRESOURCE_EMPTYBOX = 898,
		TOO_MANY_NODES_SPECIFIED = 899,
		INVALID_NODE_INDEX = 900,
		GETHEAPPROPERTIES_INVALIDRESOURCE = 901,
		NODE_MASK_MISMATCH = 902,
		COMMAND_LIST_OUTOFMEMORY = 903,
		COMMAND_LIST_MULTIPLE_SWAPCHAIN_BUFFER_REFERENCES = 904,
		COMMAND_LIST_TOO_MANY_SWAPCHAIN_REFERENCES = 905,
		COMMAND_QUEUE_TOO_MANY_SWAPCHAIN_REFERENCES = 906,
		EXECUTECOMMANDLISTS_WRONGSWAPCHAINBUFFERREFERENCE = 907,
		COMMAND_LIST_SETRENDERTARGETS_INVALIDNUMRENDERTARGETS = 908,
		CREATE_QUEUE_INVALID_TYPE = 909,
		CREATE_QUEUE_INVALID_FLAGS = 910,
		CREATESHAREDRESOURCE_INVALIDFLAGS = 911,
		CREATESHAREDRESOURCE_INVALIDFORMAT = 912,
		CREATESHAREDHEAP_INVALIDFLAGS = 913,
		REFLECTSHAREDPROPERTIES_UNRECOGNIZEDPROPERTIES = 914,
		REFLECTSHAREDPROPERTIES_INVALIDSIZE = 915,
		REFLECTSHAREDPROPERTIES_INVALIDOBJECT = 916,
		KEYEDMUTEX_INVALIDOBJECT = 917,
		KEYEDMUTEX_INVALIDKEY = 918,
		KEYEDMUTEX_WRONGSTATE = 919,
		CREATE_QUEUE_INVALID_PRIORITY = 920,
		OBJECT_DELETED_WHILE_STILL_IN_USE = 921,
		CREATEPIPELINESTATE_INVALID_FLAGS = 922,
		HEAP_ADDRESS_RANGE_HAS_NO_RESOURCE = 923,
		COMMAND_LIST_DRAW_RENDER_TARGET_DELETED = 924,
		CREATEGRAPHICSPIPELINESTATE_ALL_RENDER_TARGETS_HAVE_UNKNOWN_FORMAT = 925,
		HEAP_ADDRESS_RANGE_INTERSECTS_MULTIPLE_BUFFERS = 926,
		EXECUTECOMMANDLISTS_GPU_WRITTEN_READBACK_RESOURCE_MAPPED = 927,
		UNMAP_RANGE_NOT_EMPTY = 929,
		MAP_INVALID_NULLRANGE = 930,
		UNMAP_INVALID_NULLRANGE = 931,
		NO_GRAPHICS_API_SUPPORT = 932,
		NO_COMPUTE_API_SUPPORT = 933,
		RESOLVESUBRESOURCE_RESOURCE_FLAGS_NOT_SUPPORTED = 934,
		GPU_BASED_VALIDATION_ROOT_ARGUMENT_UNINITIALIZED = 935,
		GPU_BASED_VALIDATION_DESCRIPTOR_HEAP_INDEX_OUT_OF_BOUNDS = 936,
		GPU_BASED_VALIDATION_DESCRIPTOR_TABLE_REGISTER_INDEX_OUT_OF_BOUNDS = 937,
		GPU_BASED_VALIDATION_DESCRIPTOR_UNINITIALIZED = 938,
		GPU_BASED_VALIDATION_DESCRIPTOR_TYPE_MISMATCH = 939,
		GPU_BASED_VALIDATION_SRV_RESOURCE_DIMENSION_MISMATCH = 940,
		GPU_BASED_VALIDATION_UAV_RESOURCE_DIMENSION_MISMATCH = 941,
		GPU_BASED_VALIDATION_INCOMPATIBLE_RESOURCE_STATE = 942,
		COPYRESOURCE_NULLDST = 943,
		COPYRESOURCE_INVALIDDSTRESOURCE = 944,
		COPYRESOURCE_NULLSRC = 945,
		COPYRESOURCE_INVALIDSRCRESOURCE = 946,
		RESOLVESUBRESOURCE_NULLDST = 947,
		RESOLVESUBRESOURCE_INVALIDDSTRESOURCE = 948,
		RESOLVESUBRESOURCE_NULLSRC = 949,
		RESOLVESUBRESOURCE_INVALIDSRCRESOURCE = 950,
		PIPELINE_STATE_TYPE_MISMATCH = 951,
		COMMAND_LIST_DISPATCH_ROOT_SIGNATURE_NOT_SET = 952,
		COMMAND_LIST_DISPATCH_ROOT_SIGNATURE_MISMATCH = 953,
		RESOURCE_BARRIER_ZERO_BARRIERS = 954,
		BEGIN_END_EVENT_MISMATCH = 955,
		RESOURCE_BARRIER_POSSIBLE_BEFORE_AFTER_MISMATCH = 956,
		RESOURCE_BARRIER_MISMATCHING_BEGIN_END = 957,
		GPU_BASED_VALIDATION_INVALID_RESOURCE = 958,
		USE_OF_ZERO_REFCOUNT_OBJECT = 959,
		OBJECT_EVICTED_WHILE_STILL_IN_USE = 960,
		GPU_BASED_VALIDATION_ROOT_DESCRIPTOR_ACCESS_OUT_OF_BOUNDS = 961,
		CREATEPIPELINELIBRARY_INVALIDLIBRARYBLOB = 962,
		CREATEPIPELINELIBRARY_DRIVERVERSIONMISMATCH = 963,
		CREATEPIPELINELIBRARY_ADAPTERVERSIONMISMATCH = 964,
		CREATEPIPELINELIBRARY_UNSUPPORTED = 965,
		CREATE_PIPELINELIBRARY = 966,
		LIVE_PIPELINELIBRARY = 967,
		DESTROY_PIPELINELIBRARY = 968,
		STOREPIPELINE_NONAME = 969,
		STOREPIPELINE_DUPLICATENAME = 970,
		LOADPIPELINE_NAMENOTFOUND = 971,
		LOADPIPELINE_INVALIDDESC = 972,
		PIPELINELIBRARY_SERIALIZE_NOTENOUGHMEMORY = 973,
		CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_RT_OUTPUT_MISMATCH = 974,
		SETEVENTONMULTIPLEFENCECOMPLETION_INVALIDFLAGS = 975,
		CREATE_QUEUE_VIDEO_NOT_SUPPORTED = 976,
		CREATE_COMMAND_ALLOCATOR_VIDEO_NOT_SUPPORTED = 977,
		CREATEQUERY_HEAP_VIDEO_DECODE_STATISTICS_NOT_SUPPORTED = 978,
		CREATE_VIDEODECODECOMMANDLIST = 979,
		CREATE_VIDEODECODER = 980,
		CREATE_VIDEODECODESTREAM = 981,
		LIVE_VIDEODECODECOMMANDLIST = 982,
		LIVE_VIDEODECODER = 983,
		LIVE_VIDEODECODESTREAM = 984,
		DESTROY_VIDEODECODECOMMANDLIST = 985,
		DESTROY_VIDEODECODER = 986,
		DESTROY_VIDEODECODESTREAM = 987,
		DECODE_FRAME_INVALID_PARAMETERS = 988,
		DEPRECATED_API = 989,
		RESOURCE_BARRIER_MISMATCHING_COMMAND_LIST_TYPE = 990,
		COMMAND_LIST_DESCRIPTOR_TABLE_NOT_SET = 991,
		COMMAND_LIST_ROOT_CONSTANT_BUFFER_VIEW_NOT_SET = 992,
		COMMAND_LIST_ROOT_SHADER_RESOURCE_VIEW_NOT_SET = 993,
		COMMAND_LIST_ROOT_UNORDERED_ACCESS_VIEW_NOT_SET = 994,
		DISCARD_INVALID_SUBRESOURCE_RANGE = 995,
		DISCARD_ONE_SUBRESOURCE_FOR_MIPS_WITH_RECTS = 996,
		DISCARD_NO_RECTS_FOR_NON_TEXTURE2D = 997,
		COPY_ON_SAME_SUBRESOURCE = 998,
		SETRESIDENCYPRIORITY_INVALID_PAGEABLE = 999,
		GPU_BASED_VALIDATION_UNSUPPORTED = 1000,
		STATIC_DESCRIPTOR_INVALID_DESCRIPTOR_CHANGE = 1001,
		DATA_STATIC_DESCRIPTOR_INVALID_DATA_CHANGE = 1002,
		DATA_STATIC_WHILE_SET_AT_EXECUTE_DESCRIPTOR_INVALID_DATA_CHANGE = 1003,
		EXECUTE_BUNDLE_STATIC_DESCRIPTOR_DATA_STATIC_NOT_SET = 1004,
		GPU_BASED_VALIDATION_RESOURCE_ACCESS_OUT_OF_BOUNDS = 1005,
		GPU_BASED_VALIDATION_SAMPLER_MODE_MISMATCH = 1006,
		CREATE_FENCE_INVALID_FLAGS = 1007,
		RESOURCE_BARRIER_DUPLICATE_SUBRESOURCE_TRANSITIONS = 1008,
		SETRESIDENCYPRIORITY_INVALID_PRIORITY = 1009,
		CREATE_DESCRIPTOR_HEAP_LARGE_NUM_DESCRIPTORS = 1013,
		BEGIN_EVENT = 1014,
		END_EVENT = 1015,
		CREATEDEVICE_DEBUG_LAYER_STARTUP_OPTIONS = 1016,
		CREATEDEPTHSTENCILSTATE_DEPTHBOUNDSTEST_UNSUPPORTED = 1017,
		CREATEPIPELINESTATE_DUPLICATE_SUBOBJECT = 1018,
		CREATEPIPELINESTATE_UNKNOWN_SUBOBJECT = 1019,
		CREATEPIPELINESTATE_ZERO_SIZE_STREAM = 1020,
		CREATEPIPELINESTATE_INVALID_STREAM = 1021,
		CREATEPIPELINESTATE_CANNOT_DEDUCE_TYPE = 1022,
		COMMAND_LIST_STATIC_DESCRIPTOR_RESOURCE_DIMENSION_MISMATCH = 1023,
		CREATE_COMMAND_QUEUE_INSUFFICIENT_PRIVILEGE_FOR_GLOBAL_REALTIME = 1024,
		CREATE_COMMAND_QUEUE_INSUFFICIENT_HARDWARE_SUPPORT_FOR_GLOBAL_REALTIME = 1025,
		ATOMICCOPYBUFFER_INVALID_ARCHITECTURE = 1026,
		ATOMICCOPYBUFFER_NULL_DST = 1027,
		ATOMICCOPYBUFFER_INVALID_DST_RESOURCE_DIMENSION = 1028,
		ATOMICCOPYBUFFER_DST_RANGE_OUT_OF_BOUNDS = 1029,
		ATOMICCOPYBUFFER_NULL_SRC = 1030,
		ATOMICCOPYBUFFER_INVALID_SRC_RESOURCE_DIMENSION = 1031,
		ATOMICCOPYBUFFER_SRC_RANGE_OUT_OF_BOUNDS = 1032,
		ATOMICCOPYBUFFER_INVALID_OFFSET_ALIGNMENT = 1033,
		ATOMICCOPYBUFFER_NULL_DEPENDENT_RESOURCES = 1034,
		ATOMICCOPYBUFFER_NULL_DEPENDENT_SUBRESOURCE_RANGES = 1035,
		ATOMICCOPYBUFFER_INVALID_DEPENDENT_RESOURCE = 1036,
		ATOMICCOPYBUFFER_INVALID_DEPENDENT_SUBRESOURCE_RANGE = 1037,
		ATOMICCOPYBUFFER_DEPENDENT_SUBRESOURCE_OUT_OF_BOUNDS = 1038,
		ATOMICCOPYBUFFER_DEPENDENT_RANGE_OUT_OF_BOUNDS = 1039,
		ATOMICCOPYBUFFER_ZERO_DEPENDENCIES = 1040,
		DEVICE_CREATE_SHARED_HANDLE_INVALIDARG = 1041,
		DESCRIPTOR_HANDLE_WITH_INVALID_RESOURCE = 1042,
		SETDEPTHBOUNDS_INVALIDARGS = 1043,
		GPU_BASED_VALIDATION_RESOURCE_STATE_IMPRECISE = 1044,
		COMMAND_LIST_PIPELINE_STATE_NOT_SET = 1045,
		CREATEGRAPHICSPIPELINESTATE_SHADER_MODEL_MISMATCH = 1046,
		OBJECT_ACCESSED_WHILE_STILL_IN_USE = 1047,
		PROGRAMMABLE_MSAA_UNSUPPORTED = 1048,
		SETSAMPLEPOSITIONS_INVALIDARGS = 1049,
		RESOLVESUBRESOURCEREGION_INVALID_RECT = 1050,
		CREATE_VIDEODECODECOMMANDQUEUE = 1051,
		CREATE_VIDEOPROCESSCOMMANDLIST = 1052,
		CREATE_VIDEOPROCESSCOMMANDQUEUE = 1053,
		LIVE_VIDEODECODECOMMANDQUEUE = 1054,
		LIVE_VIDEOPROCESSCOMMANDLIST = 1055,
		LIVE_VIDEOPROCESSCOMMANDQUEUE = 1056,
		DESTROY_VIDEODECODECOMMANDQUEUE = 1057,
		DESTROY_VIDEOPROCESSCOMMANDLIST = 1058,
		DESTROY_VIDEOPROCESSCOMMANDQUEUE = 1059,
		CREATE_VIDEOPROCESSOR = 1060,
		CREATE_VIDEOPROCESSSTREAM = 1061,
		LIVE_VIDEOPROCESSOR = 1062,
		LIVE_VIDEOPROCESSSTREAM = 1063,
		DESTROY_VIDEOPROCESSOR = 1064,
		DESTROY_VIDEOPROCESSSTREAM = 1065,
		PROCESS_FRAME_INVALID_PARAMETERS = 1066,
		COPY_INVALIDLAYOUT = 1067,
		CREATE_CRYPTO_SESSION = 1068,
		CREATE_CRYPTO_SESSION_POLICY = 1069,
		CREATE_PROTECTED_RESOURCE_SESSION = 1070,
		LIVE_CRYPTO_SESSION = 1071,
		LIVE_CRYPTO_SESSION_POLICY = 1072,
		LIVE_PROTECTED_RESOURCE_SESSION = 1073,
		DESTROY_CRYPTO_SESSION = 1074,
		DESTROY_CRYPTO_SESSION_POLICY = 1075,
		DESTROY_PROTECTED_RESOURCE_SESSION = 1076,
		PROTECTED_RESOURCE_SESSION_UNSUPPORTED = 1077,
		FENCE_INVALIDOPERATION = 1078,
		CREATEQUERY_HEAP_COPY_QUEUE_TIMESTAMPS_NOT_SUPPORTED = 1079,
		SAMPLEPOSITIONS_MISMATCH_DEFERRED = 1080,
		SAMPLEPOSITIONS_MISMATCH_RECORDTIME_ASSUMEDFROMFIRSTUSE = 1081,
		SAMPLEPOSITIONS_MISMATCH_RECORDTIME_ASSUMEDFROMCLEAR = 1082,
		CREATE_VIDEODECODERHEAP = 1083,
		LIVE_VIDEODECODERHEAP = 1084,
		DESTROY_VIDEODECODERHEAP = 1085,
		OPENEXISTINGHEAP_INVALIDARG_RETURN = 1086,
		OPENEXISTINGHEAP_OUTOFMEMORY_RETURN = 1087,
		OPENEXISTINGHEAP_INVALIDADDRESS = 1088,
		OPENEXISTINGHEAP_INVALIDHANDLE = 1089,
		WRITEBUFFERIMMEDIATE_INVALID_DEST = 1090,
		WRITEBUFFERIMMEDIATE_INVALID_MODE = 1091,
		WRITEBUFFERIMMEDIATE_INVALID_ALIGNMENT = 1092,
		WRITEBUFFERIMMEDIATE_NOT_SUPPORTED = 1093,
		SETVIEWINSTANCEMASK_INVALIDARGS = 1094,
		VIEW_INSTANCING_UNSUPPORTED = 1095,
		VIEW_INSTANCING_INVALIDARGS = 1096,
		COPYTEXTUREREGION_MISMATCH_DECODE_REFERENCE_ONLY_FLAG = 1097,
		COPYRESOURCE_MISMATCH_DECODE_REFERENCE_ONLY_FLAG = 1098,
		CREATE_VIDEO_DECODE_HEAP_CAPS_FAILURE = 1099,
		CREATE_VIDEO_DECODE_HEAP_CAPS_UNSUPPORTED = 1100,
		VIDEO_DECODE_SUPPORT_INVALID_INPUT = 1101,
		CREATE_VIDEO_DECODER_UNSUPPORTED = 1102,
		CREATEGRAPHICSPIPELINESTATE_METADATA_ERROR = 1103,
		CREATEGRAPHICSPIPELINESTATE_VIEW_INSTANCING_VERTEX_SIZE_EXCEEDED = 1104,
		CREATEGRAPHICSPIPELINESTATE_RUNTIME_INTERNAL_ERROR = 1105,
		NO_VIDEO_API_SUPPORT = 1106,
		VIDEO_PROCESS_SUPPORT_INVALID_INPUT = 1107,
		CREATE_VIDEO_PROCESSOR_CAPS_FAILURE = 1108,
		VIDEO_PROCESS_SUPPORT_UNSUPPORTED_FORMAT = 1109,
		VIDEO_DECODE_FRAME_INVALID_ARGUMENT = 1110,
		ENQUEUE_MAKE_RESIDENT_INVALID_FLAGS = 1111,
		OPENEXISTINGHEAP_UNSUPPORTED = 1112,
		VIDEO_PROCESS_FRAMES_INVALID_ARGUMENT = 1113,
		VIDEO_DECODE_SUPPORT_UNSUPPORTED = 1114,
		CREATE_COMMANDRECORDER = 1115,
		LIVE_COMMANDRECORDER = 1116,
		DESTROY_COMMANDRECORDER = 1117,
		CREATE_COMMAND_RECORDER_VIDEO_NOT_SUPPORTED = 1118,
		CREATE_COMMAND_RECORDER_INVALID_SUPPORT_FLAGS = 1119,
		CREATE_COMMAND_RECORDER_INVALID_FLAGS = 1120,
		CREATE_COMMAND_RECORDER_MORE_RECORDERS_THAN_LOGICAL_PROCESSORS = 1121,
		CREATE_COMMANDPOOL = 1122,
		LIVE_COMMANDPOOL = 1123,
		DESTROY_COMMANDPOOL = 1124,
		CREATE_COMMAND_POOL_INVALID_FLAGS = 1125,
		CREATE_COMMAND_LIST_VIDEO_NOT_SUPPORTED = 1126,
		COMMAND_RECORDER_SUPPORT_FLAGS_MISMATCH = 1127,
		COMMAND_RECORDER_CONTENTION = 1128,
		COMMAND_RECORDER_USAGE_WITH_CREATECOMMANDLIST_COMMAND_LIST = 1129,
		COMMAND_ALLOCATOR_USAGE_WITH_CREATECOMMANDLIST1_COMMAND_LIST = 1130,
		CANNOT_EXECUTE_EMPTY_COMMAND_LIST = 1131,
		CANNOT_RESET_COMMAND_POOL_WITH_OPEN_COMMAND_LISTS = 1132,
		CANNOT_USE_COMMAND_RECORDER_WITHOUT_CURRENT_TARGET = 1133,
		CANNOT_CHANGE_COMMAND_RECORDER_TARGET_WHILE_RECORDING = 1134,
		COMMAND_POOL_SYNC = 1135,
		EVICT_UNDERFLOW = 1136,
		CREATE_META_COMMAND = 1137,
		LIVE_META_COMMAND = 1138,
		DESTROY_META_COMMAND = 1139,
		COPYBUFFERREGION_INVALID_DST_RESOURCE = 1140,
		COPYBUFFERREGION_INVALID_SRC_RESOURCE = 1141,
		ATOMICCOPYBUFFER_INVALID_DST_RESOURCE = 1142,
		ATOMICCOPYBUFFER_INVALID_SRC_RESOURCE = 1143,
		CREATEPLACEDRESOURCEONBUFFER_NULL_BUFFER = 1144,
		CREATEPLACEDRESOURCEONBUFFER_NULL_RESOURCE_DESC = 1145,
		CREATEPLACEDRESOURCEONBUFFER_UNSUPPORTED = 1146,
		CREATEPLACEDRESOURCEONBUFFER_INVALID_BUFFER_DIMENSION = 1147,
		CREATEPLACEDRESOURCEONBUFFER_INVALID_BUFFER_FLAGS = 1148,
		CREATEPLACEDRESOURCEONBUFFER_INVALID_BUFFER_OFFSET = 1149,
		CREATEPLACEDRESOURCEONBUFFER_INVALID_RESOURCE_DIMENSION = 1150,
		CREATEPLACEDRESOURCEONBUFFER_INVALID_RESOURCE_FLAGS = 1151,
		CREATEPLACEDRESOURCEONBUFFER_OUTOFMEMORY_RETURN = 1152,
		CANNOT_CREATE_GRAPHICS_AND_VIDEO_COMMAND_RECORDER = 1153,
		UPDATETILEMAPPINGS_POSSIBLY_MISMATCHING_PROPERTIES = 1154,
		CREATE_COMMAND_LIST_INVALID_COMMAND_LIST_TYPE = 1155,
		CLEARUNORDEREDACCESSVIEW_INCOMPATIBLE_WITH_STRUCTURED_BUFFERS = 1156,
		COMPUTE_ONLY_DEVICE_OPERATION_UNSUPPORTED = 1157,
		BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INVALID = 1158,
		EMIT_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_INVALID = 1159,
		COPY_RAYTRACING_ACCELERATION_STRUCTURE_INVALID = 1160,
		DISPATCH_RAYS_INVALID = 1161,
		GET_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO_INVALID = 1162,
		CREATE_LIFETIMETRACKER = 1163,
		LIVE_LIFETIMETRACKER = 1164,
		DESTROY_LIFETIMETRACKER = 1165,
		DESTROYOWNEDOBJECT_OBJECTNOTOWNED = 1166,
		CREATE_TRACKEDWORKLOAD = 1167,
		LIVE_TRACKEDWORKLOAD = 1168,
		DESTROY_TRACKEDWORKLOAD = 1169,
		RENDER_PASS_ERROR = 1170,
		META_COMMAND_ID_INVALID = 1171,
		META_COMMAND_UNSUPPORTED_PARAMS = 1172,
		META_COMMAND_FAILED_ENUMERATION = 1173,
		META_COMMAND_PARAMETER_SIZE_MISMATCH = 1174,
		UNINITIALIZED_META_COMMAND = 1175,
		META_COMMAND_INVALID_GPU_VIRTUAL_ADDRESS = 1176,
		CREATE_VIDEOENCODECOMMANDLIST = 1177,
		LIVE_VIDEOENCODECOMMANDLIST = 1178,
		DESTROY_VIDEOENCODECOMMANDLIST = 1179,
		CREATE_VIDEOENCODECOMMANDQUEUE = 1180,
		LIVE_VIDEOENCODECOMMANDQUEUE = 1181,
		DESTROY_VIDEOENCODECOMMANDQUEUE = 1182,
		CREATE_VIDEOMOTIONESTIMATOR = 1183,
		LIVE_VIDEOMOTIONESTIMATOR = 1184,
		DESTROY_VIDEOMOTIONESTIMATOR = 1185,
		CREATE_VIDEOMOTIONVECTORHEAP = 1186,
		LIVE_VIDEOMOTIONVECTORHEAP = 1187,
		DESTROY_VIDEOMOTIONVECTORHEAP = 1188,
		MULTIPLE_TRACKED_WORKLOADS = 1189,
		MULTIPLE_TRACKED_WORKLOAD_PAIRS = 1190,
		OUT_OF_ORDER_TRACKED_WORKLOAD_PAIR = 1191,
		CANNOT_ADD_TRACKED_WORKLOAD = 1192,
		INCOMPLETE_TRACKED_WORKLOAD_PAIR = 1193,
		CREATE_STATE_OBJECT_ERROR = 1194,
		GET_SHADER_IDENTIFIER_ERROR = 1195,
		GET_SHADER_STACK_SIZE_ERROR = 1196,
		GET_PIPELINE_STACK_SIZE_ERROR = 1197,
		SET_PIPELINE_STACK_SIZE_ERROR = 1198,
		GET_SHADER_IDENTIFIER_SIZE_INVALID = 1199,
		CHECK_DRIVER_MATCHING_IDENTIFIER_INVALID = 1200,
		CHECK_DRIVER_MATCHING_IDENTIFIER_DRIVER_REPORTED_ISSUE = 1201,
		RENDER_PASS_INVALID_RESOURCE_BARRIER = 1202,
		RENDER_PASS_DISALLOWED_API_CALLED = 1203,
		RENDER_PASS_CANNOT_NEST_RENDER_PASSES = 1204,
		RENDER_PASS_CANNOT_END_WITHOUT_BEGIN = 1205,
		RENDER_PASS_CANNOT_CLOSE_COMMAND_LIST = 1206,
		RENDER_PASS_GPU_WORK_WHILE_SUSPENDED = 1207,
		RENDER_PASS_MISMATCHING_SUSPEND_RESUME = 1208,
		RENDER_PASS_NO_PRIOR_SUSPEND_WITHIN_EXECUTECOMMANDLISTS = 1209,
		RENDER_PASS_NO_SUBSEQUENT_RESUME_WITHIN_EXECUTECOMMANDLISTS = 1210,
		TRACKED_WORKLOAD_COMMAND_QUEUE_MISMATCH = 1211,
		TRACKED_WORKLOAD_NOT_SUPPORTED = 1212,
		RENDER_PASS_MISMATCHING_NO_ACCESS = 1213,
		RENDER_PASS_UNSUPPORTED_RESOLVE = 1214,
		CLEARUNORDEREDACCESSVIEW_INVALID_RESOURCE_PTR = 1215,
		WINDOWS7_FENCE_OUTOFORDER_SIGNAL = 1216,
		WINDOWS7_FENCE_OUTOFORDER_WAIT = 1217,
		VIDEO_CREATE_MOTION_ESTIMATOR_INVALID_ARGUMENT = 1218,
		VIDEO_CREATE_MOTION_VECTOR_HEAP_INVALID_ARGUMENT = 1219,
		ESTIMATE_MOTION_INVALID_ARGUMENT = 1220,
		RESOLVE_MOTION_VECTOR_HEAP_INVALID_ARGUMENT = 1221,
		GETGPUVIRTUALADDRESS_INVALID_HEAP_TYPE = 1222,
		SET_BACKGROUND_PROCESSING_MODE_INVALID_ARGUMENT = 1223,
		CREATE_COMMAND_LIST_INVALID_COMMAND_LIST_TYPE_FOR_FEATURE_LEVEL = 1224,
		CREATE_VIDEOEXTENSIONCOMMAND = 1225,
		LIVE_VIDEOEXTENSIONCOMMAND = 1226,
		DESTROY_VIDEOEXTENSIONCOMMAND = 1227,
		INVALID_VIDEO_EXTENSION_COMMAND_ID = 1228,
		VIDEO_EXTENSION_COMMAND_INVALID_ARGUMENT = 1229,
		CREATE_ROOT_SIGNATURE_NOT_UNIQUE_IN_DXIL_LIBRARY = 1230,
		VARIABLE_SHADING_RATE_NOT_ALLOWED_WITH_TIR = 1231,
		GEOMETRY_SHADER_OUTPUTTING_BOTH_VIEWPORT_ARRAY_INDEX_AND_SHADING_RATE_NOT_SUPPORTED_ON_DEVICE = 1232,
		RSSETSHADING_RATE_INVALID_SHADING_RATE = 1233,
		RSSETSHADING_RATE_SHADING_RATE_NOT_PERMITTED_BY_CAP = 1234,
		RSSETSHADING_RATE_INVALID_COMBINER = 1235,
		RSSETSHADINGRATEIMAGE_REQUIRES_TIER_2 = 1236,
		RSSETSHADINGRATE_REQUIRES_TIER_1 = 1237,
		SHADING_RATE_IMAGE_INCORRECT_FORMAT = 1238,
		SHADING_RATE_IMAGE_INCORRECT_ARRAY_SIZE = 1239,
		SHADING_RATE_IMAGE_INCORRECT_MIP_LEVEL = 1240,
		SHADING_RATE_IMAGE_INCORRECT_SAMPLE_COUNT = 1241,
		SHADING_RATE_IMAGE_INCORRECT_SAMPLE_QUALITY = 1242,
		NON_RETAIL_SHADER_MODEL_WONT_VALIDATE = 1243,
		CREATEGRAPHICSPIPELINESTATE_AS_ROOT_SIGNATURE_MISMATCH = 1244,
		CREATEGRAPHICSPIPELINESTATE_MS_ROOT_SIGNATURE_MISMATCH = 1245,
		ADD_TO_STATE_OBJECT_ERROR = 1246,
		CREATE_PROTECTED_RESOURCE_SESSION_INVALID_ARGUMENT = 1247,
		CREATEGRAPHICSPIPELINESTATE_MS_PSO_DESC_MISMATCH = 1248,
		CREATEPIPELINESTATE_MS_INCOMPLETE_TYPE = 1249,
		CREATEGRAPHICSPIPELINESTATE_AS_NOT_MS_MISMATCH = 1250,
		CREATEGRAPHICSPIPELINESTATE_MS_NOT_PS_MISMATCH = 1251,
		NONZERO_SAMPLER_FEEDBACK_MIP_REGION_WITH_INCOMPATIBLE_FORMAT = 1252,
		CREATEGRAPHICSPIPELINESTATE_INPUTLAYOUT_SHADER_MISMATCH = 1253,
		EMPTY_DISPATCH = 1254,
		RESOURCE_FORMAT_REQUIRES_SAMPLER_FEEDBACK_CAPABILITY = 1255,
		SAMPLER_FEEDBACK_MAP_INVALID_MIP_REGION = 1256,
		SAMPLER_FEEDBACK_MAP_INVALID_DIMENSION = 1257,
		SAMPLER_FEEDBACK_MAP_INVALID_SAMPLE_COUNT = 1258,
		SAMPLER_FEEDBACK_MAP_INVALID_SAMPLE_QUALITY = 1259,
		SAMPLER_FEEDBACK_MAP_INVALID_LAYOUT = 1260,
		SAMPLER_FEEDBACK_MAP_REQUIRES_UNORDERED_ACCESS_FLAG = 1261,
		SAMPLER_FEEDBACK_CREATE_UAV_NULL_ARGUMENTS = 1262,
		SAMPLER_FEEDBACK_UAV_REQUIRES_SAMPLER_FEEDBACK_CAPABILITY = 1263,
		SAMPLER_FEEDBACK_CREATE_UAV_REQUIRES_FEEDBACK_MAP_FORMAT = 1264,
		CREATEMESHSHADER_INVALIDSHADERBYTECODE = 1265,
		CREATEMESHSHADER_OUTOFMEMORY = 1266,
		CREATEMESHSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE = 1267,
		RESOLVESUBRESOURCE_SAMPLER_FEEDBACK_TRANSCODE_INVALID_FORMAT = 1268,
		RESOLVESUBRESOURCE_SAMPLER_FEEDBACK_INVALID_MIP_LEVEL_COUNT = 1269,
		RESOLVESUBRESOURCE_SAMPLER_FEEDBACK_TRANSCODE_ARRAY_SIZE_MISMATCH = 1270,
		SAMPLER_FEEDBACK_CREATE_UAV_MISMATCHING_TARGETED_RESOURCE = 1271,
		CREATEMESHSHADER_OUTPUTEXCEEDSMAXSIZE = 1272,
		CREATEMESHSHADER_GROUPSHAREDEXCEEDSMAXSIZE = 1273,
		VERTEX_SHADER_OUTPUTTING_BOTH_VIEWPORT_ARRAY_INDEX_AND_SHADING_RATE_NOT_SUPPORTED_ON_DEVICE = 1274,
		MESH_SHADER_OUTPUTTING_BOTH_VIEWPORT_ARRAY_INDEX_AND_SHADING_RATE_NOT_SUPPORTED_ON_DEVICE = 1275,
		CREATEMESHSHADER_MISMATCHEDASMSPAYLOADSIZE = 1276,
		CREATE_ROOT_SIGNATURE_UNBOUNDED_STATIC_DESCRIPTORS = 1277,
		CREATEAMPLIFICATIONSHADER_INVALIDSHADERBYTECODE = 1278,
		CREATEAMPLIFICATIONSHADER_OUTOFMEMORY = 1279,
		CREATE_SHADERCACHESESSION = 1280,
		LIVE_SHADERCACHESESSION = 1281,
		DESTROY_SHADERCACHESESSION = 1282,
		CREATESHADERCACHESESSION_INVALIDARGS = 1283,
		CREATESHADERCACHESESSION_DISABLED = 1284,
		CREATESHADERCACHESESSION_ALREADYOPEN = 1285,
		SHADERCACHECONTROL_DEVELOPERMODE = 1286,
		SHADERCACHECONTROL_INVALIDFLAGS = 1287,
		SHADERCACHECONTROL_STATEALREADYSET = 1288,
		SHADERCACHECONTROL_IGNOREDFLAG = 1289,
		SHADERCACHESESSION_STOREVALUE_ALREADYPRESENT = 1290,
		SHADERCACHESESSION_STOREVALUE_HASHCOLLISION = 1291,
		SHADERCACHESESSION_STOREVALUE_CACHEFULL = 1292,
		SHADERCACHESESSION_FINDVALUE_NOTFOUND = 1293,
		SHADERCACHESESSION_CORRUPT = 1294,
		SHADERCACHESESSION_DISABLED = 1295,
		OVERSIZED_DISPATCH = 1296,
		CREATE_VIDEOENCODER = 1297,
		LIVE_VIDEOENCODER = 1298,
		DESTROY_VIDEOENCODER = 1299,
		CREATE_VIDEOENCODERHEAP = 1300,
		LIVE_VIDEOENCODERHEAP = 1301,
		DESTROY_VIDEOENCODERHEAP = 1302,
		COPYTEXTUREREGION_MISMATCH_ENCODE_REFERENCE_ONLY_FLAG = 1303,
		COPYRESOURCE_MISMATCH_ENCODE_REFERENCE_ONLY_FLAG = 1304,
		ENCODE_FRAME_INVALID_PARAMETERS = 1305,
		ENCODE_FRAME_UNSUPPORTED_PARAMETERS = 1306,
		RESOLVE_ENCODER_OUTPUT_METADATA_INVALID_PARAMETERS = 1307,
		RESOLVE_ENCODER_OUTPUT_METADATA_UNSUPPORTED_PARAMETERS = 1308,
		CREATE_VIDEO_ENCODER_INVALID_PARAMETERS = 1309,
		CREATE_VIDEO_ENCODER_UNSUPPORTED_PARAMETERS = 1310,
		CREATE_VIDEO_ENCODER_HEAP_INVALID_PARAMETERS = 1311,
		CREATE_VIDEO_ENCODER_HEAP_UNSUPPORTED_PARAMETERS = 1312,
		CREATECOMMANDLIST_NULL_COMMANDALLOCATOR,
		CLEAR_UNORDERED_ACCESS_VIEW_INVALID_DESCRIPTOR_HANDLE,
		DESCRIPTOR_HEAP_NOT_SHADER_VISIBLE,
		CREATEBLENDSTATE_BLENDOP_WARNING,
		CREATEBLENDSTATE_BLENDOPALPHA_WARNING,
		WRITE_COMBINE_PERFORMANCE_WARNING,
		RESOLVE_QUERY_INVALID_QUERY_STATE,
		SETPRIVATEDATA_NO_ACCESS,
		COMMAND_LIST_STATIC_DESCRIPTOR_SAMPLER_MODE_MISMATCH,
		GETCOPYABLEFOOTPRINTS_UNSUPPORTED_BUFFER_WIDTH,
		CREATEMESHSHADER_TOPOLOGY_MISMATCH,
		VRS_SUM_COMBINER_REQUIRES_CAPABILITY,
		SETTING_SHADING_RATE_FROM_MS_REQUIRES_CAPABILITY,
		SHADERCACHESESSION_SHADERCACHEDELETE_NOTSUPPORTED,
		SHADERCACHECONTROL_SHADERCACHECLEAR_NOTSUPPORTED,
		CREATERESOURCE_STATE_IGNORED,
		UNUSED_CROSS_EXECUTE_SPLIT_BARRIER,
		DEVICE_OPEN_SHARED_HANDLE_ACCESS_DENIED,
		INCOMPATIBLE_BARRIER_VALUES,
		INCOMPATIBLE_BARRIER_ACCESS,
		INCOMPATIBLE_BARRIER_SYNC,
		INCOMPATIBLE_BARRIER_LAYOUT,
		INCOMPATIBLE_BARRIER_TYPE,
		OUT_OF_BOUNDS_BARRIER_SUBRESOURCE_RANGE,
		INCOMPATIBLE_BARRIER_RESOURCE_DIMENSION,
		SET_SCISSOR_RECTS_INVALID_RECT,
		SHADING_RATE_SOURCE_REQUIRES_DIMENSION_TEXTURE2D,
		BUFFER_BARRIER_SUBREGION_OUT_OF_BOUNDS,
		UNSUPPORTED_BARRIER_LAYOUT,
		CREATERESOURCEANDHEAP_INVALID_PARAMETERS,
		ENHANCED_BARRIERS_NOT_SUPPORTED,
		LEGACY_BARRIER_VALIDATION_FORCED_ON,
		EMPTY_ROOT_DESCRIPTOR_TABLE,
		COMMAND_LIST_DRAW_ELEMENT_OFFSET_UNALIGNED,
		ALPHA_BLEND_FACTOR_NOT_SUPPORTED,
		BARRIER_INTEROP_INVALID_LAYOUT,
		BARRIER_INTEROP_INVALID_STATE,
		GRAPHICS_PIPELINE_STATE_DESC_ZERO_SAMPLE_MASK,
		INDEPENDENT_STENCIL_REF_NOT_SUPPORTED,
		CREATEDEPTHSTENCILSTATE_INDEPENDENT_MASKS_UNSUPPORTED,
		TEXTURE_BARRIER_SUBRESOURCES_OUT_OF_BOUNDS,
		NON_OPTIMAL_BARRIER_ONLY_EXECUTE_COMMAND_LISTS,
		EXECUTE_INDIRECT_ZERO_COMMAND_COUNT,
		GPU_BASED_VALIDATION_INCOMPATIBLE_TEXTURE_LAYOUT,
		DYNAMIC_INDEX_BUFFER_STRIP_CUT_NOT_SUPPORTED,
		PRIMITIVE_TOPOLOGY_TRIANGLE_FANS_NOT_SUPPORTED,
		CREATE_SAMPLER_COMPARISON_FUNC_IGNORED,
		CREATEHEAP_INVALIDHEAPTYPE,
		CREATERESOURCEANDHEAP_INVALIDHEAPTYPE,
		DYNAMIC_DEPTH_BIAS_NOT_SUPPORTED,
		CREATERASTERIZERSTATE_NON_WHOLE_DYNAMIC_DEPTH_BIAS,
		DYNAMIC_DEPTH_BIAS_FLAG_MISSING,
		DYNAMIC_DEPTH_BIAS_NO_PIPELINE,
		DYNAMIC_INDEX_BUFFER_STRIP_CUT_FLAG_MISSING,
		DYNAMIC_INDEX_BUFFER_STRIP_CUT_NO_PIPELINE,
		NONNORMALIZED_COORDINATE_SAMPLING_NOT_SUPPORTED,
		INVALID_CAST_TARGET,
		RENDER_PASS_COMMANDLIST_INVALID_END_STATE,
		RENDER_PASS_COMMANDLIST_INVALID_START_STATE,
		RENDER_PASS_MISMATCHING_ACCESS,
		RENDER_PASS_MISMATCHING_LOCAL_PRESERVE_PARAMETERS,
		RENDER_PASS_LOCAL_PRESERVE_RENDER_PARAMETERS_ERROR,
		RENDER_PASS_LOCAL_DEPTH_STENCIL_ERROR,
		DRAW_POTENTIALLY_OUTSIDE_OF_VALID_RENDER_AREA,
		CREATERASTERIZERSTATE_INVALID_LINERASTERIZATIONMODE,
		CREATERESOURCE_INVALIDALIGNMENT_SMALLRESOURCE,
		GENERIC_DEVICE_OPERATION_UNSUPPORTED,
		CREATEGRAPHICSPIPELINESTATE_RENDER_TARGET_WRONG_WRITE_MASK,
		PROBABLE_PIX_EVENT_LEAK,
		PIX_EVENT_UNDERFLOW,
		RECREATEAT_INVALID_TARGET,
		RECREATEAT_INSUFFICIENT_SUPPORT,
		GPU_BASED_VALIDATION_STRUCTURED_BUFFER_STRIDE_MISMATCH,
		D3D12_MESSAGES_END
	};

	class TR_CLASS()
		IGpuSystem : public IWeakRefObject
	{
	public:
		static IGpuSystem* CreateGpuSystem(ERhiType type, const FGpuSystemDesc* desc);
		virtual bool InitGpuSystem(ERhiType type, const FGpuSystemDesc * desc) { return true; }
		virtual IGpuDevice* CreateDevice(const FGpuDeviceDesc * desc) = 0;
		virtual int GetNumOfGpuDevice() const{
			return 1;
		}
		virtual void GetDeviceDesc(int index, FGpuDeviceDesc* desc) const {

		}
	public:
		ERhiType		Type = ERhiType::RHI_D3D11;
		FGpuSystemDesc	Desc{};
	};
	struct TR_CLASS(SV_LayoutStruct = 8)
		FGpuDeviceDesc
	{
		void SetDefault()
		{
			RhiType = ERhiType::RHI_D3D11;
			memset(Name, 0, sizeof(Name));
			VendorId = 0;
			AdapterId = 0;
			DeviceHandle = nullptr;
			DeviceContextHandle = nullptr;
			CreateDebugLayer = true;
			IsGpuDred = true;
			IsAftermath = false;
		}
		bool IsNVIDIA() const{
			return 0x10DE == VendorId;
		}
		bool IsIntel() const {
			return 0x8086 == VendorId;
		}
		bool IsAMD() const {
			return 0x1002 == VendorId;
		}
		ERhiType	RhiType = ERhiType::RHI_D3D11;
		char	Name[256]{};
		int		VendorId;
		int		AdapterId = 0;
		UINT64	DedicatedVideoMemory = 0;
		void*	DeviceHandle = nullptr;
		void*	DeviceContextHandle = nullptr;
		bool	CreateDebugLayer = true;
		bool	IsGpuDred = true;
		bool	IsAftermath = false;

		const char* GetName() const {
			return Name;
		}
	};
	struct TR_CLASS(SV_LayoutStruct = 8)
		FGpuDeviceCaps
	{
		bool	IsSupportFence = false;
		bool	IsSupportSSBO_VS = true;
		bool	IsSupportBufferToTexture = false;
		bool	IsSupportMeshShader = false;
		bool	IsSupportRayTracing = false;
		UINT			MaxViewInstanceCount = 0;
		UINT			NumOfSwapchainFormats = 0;
		EPixelFormat	SwapchainFormats[16] = {};
		bool IsSupportSwapchainFormat(EPixelFormat format) const
		{
			for (UINT i = 0; i < NumOfSwapchainFormats; i++)
			{
				if (SwapchainFormats[i] == format)
				{
					return true;
				}
			}
			return false;
		}
	};
	struct TR_CLASS(SV_LayoutStruct = 8)
		FGpuResourceAlignment
	{
		UINT CBufferAlignment = 1;
		UINT VbIbAlignment = 1;
		UINT SsbAlignment = 1;
		UINT TexturePitchAlignment = 1;
		UINT TextureAlignment = 1;
		UINT MsaaAlignment = 1;
		UINT RawSrvUavAlignment = 1;
		UINT UavCounterAlignment = 1;
		UINT RoundupTexturePitch(UINT x) const
		{
			return TexturePitchAlignment * ((x + (TexturePitchAlignment - 1)) / TexturePitchAlignment);
		}
	};
	template<class _DestroyType>
	struct AuxGpuResourceDestroyer
	{
		static void Destroy(_DestroyType obj, IGpuDevice* device)
		{

		}
	};
	class TR_CLASS()
		IGpuDevice : public IWeakRefObject
	{
	protected:
		static bool mIsTryFinalize;
		bool mIsFinalized = false;
	public:
		ENGINE_RTTI(IGpuDevice);
		IGpuDevice();
		virtual bool InitDevice(IGpuSystem * pGpuSystem, const FGpuDeviceDesc * desc) = 0;
		virtual void TryFinalizeDevice(IGpuSystem * pGpuSystem) {
			mIsTryFinalize = true;
			mIsFinalized = false;
		}
		static bool IsTryFinalize() {
			return mIsTryFinalize;
		}
		bool IsFinalized() const{
			return mIsFinalized;
		}
		virtual IBuffer* CreateBuffer(const FBufferDesc * desc) = 0;
		virtual ITexture* CreateTexture(const FTextureDesc * desc) = 0;
		virtual ITexture* CreateTexture(void* pSharedObject) { return nullptr; }
		virtual ICbView* CreateCBV(IBuffer* pBuffer, const FCbvDesc * desc) = 0;
		virtual IVbView* CreateVBV(IBuffer* pBuffer, const FVbvDesc * desc) = 0;
		virtual IIbView* CreateIBV(IBuffer* pBuffer, const FIbvDesc * desc) = 0;
		virtual ISrView* CreateSRV(IGpuBufferData * pBuffer, const FSrvDesc * desc) = 0;
		virtual IUaView* CreateUAV(IGpuBufferData * pBuffer, const FUavDesc * desc) = 0;
		virtual IRenderTargetView* CreateRTV(ITexture * pBuffer, const FRtvDesc* desc) = 0;
		virtual IDepthStencilView* CreateDSV(ITexture * pBuffer, const FDsvDesc* desc) = 0;
		virtual ISampler* CreateSampler(const FSamplerDesc * desc) = 0;
		virtual ISwapChain* CreateSwapChain(const FSwapChainDesc * desc) = 0;
		virtual IRenderPass* CreateRenderPass(const FRenderPassDesc * desc) = 0;
		virtual IFrameBuffers* CreateFrameBuffers(IRenderPass* rpass) = 0;
		virtual IAccelerationStructure* CreateAccelerationStructure(const FAccelerationStructureDesc* desc) = 0;
		virtual IAStructureInstance* CreateAccelerationStructureInstance(const FAStructureInstanceDesc* desc, IAccelerationStructure* pAStructrure) = 0;
		virtual ITopAccelerationStructure* CreateTopAccelerationStructure(const FTopAccelerationStructureDesc* desc) = 0;
		
		virtual IGpuPipeline* CreatePipeline(const FGpuPipelineDesc * desc) = 0;
		virtual IGpuDrawState* CreateGpuDrawState() = 0;
		virtual IInputLayout* CreateInputLayout(FInputLayoutDesc* desc) = 0;
		virtual ICommandList* CreateCommandList() = 0;
		virtual IShader* CreateShader(FShaderDesc* desc) = 0;
		virtual IGraphicsEffect* CreateShaderEffect() = 0;
		virtual IComputeEffect* CreateComputeEffect() = 0;
		virtual IRayTracingEffect* CreateRayTracingEffect() { return nullptr; }
		virtual IFence* CreateFence(const FFenceDesc* desc, const char* name) = 0;
		virtual IEvent* CreateGpuEvent(const FEventDesc * desc, const char* name) = 0;
		virtual ICmdQueue* GetCmdQueue() = 0;

		virtual IGraphicDraw* CreateGraphicDraw();
		virtual IComputeDraw* CreateComputeDraw();
		virtual IRayTracingDraw* CreateRayTracingDraw();
		virtual ICopyDraw* CreateCopyDraw();
		virtual IActionDraw* CreateActionDraw();

		virtual FVertexArray* CreateVertexArray();
		virtual FGeomMesh* CreateGeomMesh();
		virtual IGpuScope* CreateGpuScope() = 0;
		inline const FGpuResourceAlignment* GetGpuResourceAlignment() const{
			return &mGpuResourceAlignment;
		}
		inline const FGpuDeviceCaps* GetGpuDeviceCaps() const {
			return &mCaps;
		}
		inline bool IsSupportSwapchainFormat(EPixelFormat format) const {
			return mCaps.IsSupportSwapchainFormat(format);
		}
		FGpuPipelineManager* GetGpuPipelineManager();

		virtual void SetBreakOnID(int id, bool open) = 0;
		virtual void ShowDeviceMessage(int id, bool show){}

		inline IFence* GetFrameFence() {
			return mFrameFence;
		}
	public:
		FGpuDeviceDesc		Desc;
		FGpuDeviceCaps		mCaps;
		FGpuResourceAlignment	mGpuResourceAlignment{};
		
		AutoRef<FGpuPipelineManager>	mPipelineManager;
		AutoRef<IFence>					mFrameFence;
		
		bool				EnableImmExecute = false;
		void*				mDeviceThreadId = nullptr;
		bool				IsSyncStage = false;
		inline void CheckDeviceThread()
		{
#if DEBUG
			ASSERT(IsSyncStage || mDeviceThreadId == vfxThread::GetCurrentThreadId());
#endif
		}
	public:
		typedef bool (FGpuPostEvent)(IGpuDevice* device, UINT64 completed);
		std::vector<std::function<FGpuPostEvent>>	mPostEvents;
		std::vector<std::function<FGpuPostEvent>>	mTickingPostEvents;
		VSLLock mPostEventLocker;
		void PushPostEvent(const std::function<FGpuPostEvent>& evt)
		{
			VAutoVSLLock lk(mPostEventLocker);
			mPostEvents.push_back(evt);
		}
		template<class _DestroyType>
		void DelayDestroy(_DestroyType obj, UINT delayFrame = 4)
		{
			if (mIsTryFinalize == true)
			{
				AuxGpuResourceDestroyer<_DestroyType>::Destroy(obj, this);
				return;
			}
			auto targetValue = mFrameFence->GetExpectValue() + delayFrame;
			this->PushPostEvent([targetValue, obj](IGpuDevice* pDevice, UINT64 completed)->bool
				{
					if (completed >= targetValue)
					{
						AuxGpuResourceDestroyer<_DestroyType>::Destroy(obj, pDevice);
						return true;
					}
					return false;
				});
		}
		virtual void TickPostEvents();
		void WaitFrameFence(int beforeFrame = 3);
	};
	class TR_CLASS()
		ICmdQueue : public IWeakRefObject
	{
	public:
		ENGINE_RTTI(ICmdQueue);

		void ExecuteCommandListSingle(ICommandList * pCmdlist, EQueueType type)
		{
			ExecuteCommandList(1, &pCmdlist, 0, nullptr, type);
		}
		//NumOfWait = 0: No wait
		//NumOfWait = 0xFFFFFFFF: Prev Queued Cmdlist
		virtual void ExecuteCommandList(UINT NumOfExe, ICommandList** Cmdlist, UINT NumOfWait, ICommandList** ppWaitCmdlists, EQueueType type) = 0;
		virtual ICommandList* GetIdleCmdlist() = 0;
		virtual void ReleaseIdleCmdlist(ICommandList* cmd) = 0;
		virtual UINT64 Flush(EQueueType type) = 0;
		
		inline UINT64 IncreaseSignal(IFence* fence, EQueueType type)
		{
			return fence->IncreaseExpect(this, 1, type);
		}
	public:
		VCritical						mGraphicsQueueLocker;
		
		UINT64							mDefaultQueueFrequence = 0;
		UINT64							mComputeQueueFrequence = 0;
		UINT64							mTransferQueueFrequence = 0;
	};
}

NS_END