<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>False</PublishAot>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Engine.Window\Engine.Window.csproj" />
  </ItemGroup>
	
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\binaries\</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;PWindow</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>full</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\binaries\</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;PWindow</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>full</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
