#pragma once

#include "../NxGpuDevice.h"

#pragma warning(push)
#pragma warning(disable:4005)
#include <d3d11.h>
#include <d3d11_1.h>
#include <d3d11_4.h>
//#include <d3dx11.h>
#include <d3dcompiler.h>
#pragma warning(pop)

NS_BEGIN

namespace NxRHI
{
#define DXGI_FORMAT_ASTC_4X4_TYPELESS     DXGI_FORMAT(133)
#define DXGI_FORMAT_ASTC_4X4_UNORM        DXGI_FORMAT(134)
#define DXGI_FORMAT_ASTC_4X4_UNORM_SRGB   DXGI_FORMAT(135)
#define DXGI_FORMAT_ASTC_5X4_TYPELESS     DXGI_FORMAT(137)
#define DXGI_FORMAT_ASTC_5X4_UNORM        DXGI_FORMAT(138)
#define DXGI_FORMAT_ASTC_5X4_UNORM_SRGB   DXGI_FORMAT(139)
#define DXGI_FORMAT_ASTC_5X5_TYPELESS     DXGI_FORMAT(141)
#define DXGI_FORMAT_ASTC_5X5_UNORM        DXGI_FORMAT(142)
#define DXGI_FORMAT_ASTC_5X5_UNORM_SRGB   DXGI_FORMAT(143)
#define DXGI_FORMAT_ASTC_6X5_TYPELESS     DXGI_FORMAT(145)
#define DXGI_FORMAT_ASTC_6X5_UNORM        DXGI_FORMAT(146)
#define DXGI_FORMAT_ASTC_6X5_UNORM_SRGB   DXGI_FORMAT(147)
#define DXGI_FORMAT_ASTC_6X6_TYPELESS     DXGI_FORMAT(149)
#define DXGI_FORMAT_ASTC_6X6_UNORM        DXGI_FORMAT(150)
#define DXGI_FORMAT_ASTC_6X6_UNORM_SRGB   DXGI_FORMAT(151)
#define DXGI_FORMAT_ASTC_8X5_TYPELESS     DXGI_FORMAT(153)
#define DXGI_FORMAT_ASTC_8X5_UNORM        DXGI_FORMAT(154)
#define DXGI_FORMAT_ASTC_8X5_UNORM_SRGB   DXGI_FORMAT(155)
#define DXGI_FORMAT_ASTC_8X6_TYPELESS     DXGI_FORMAT(157)
#define DXGI_FORMAT_ASTC_8X6_UNORM        DXGI_FORMAT(158)
#define DXGI_FORMAT_ASTC_8X6_UNORM_SRGB   DXGI_FORMAT(159)
#define DXGI_FORMAT_ASTC_8X8_TYPELESS     DXGI_FORMAT(161)
#define DXGI_FORMAT_ASTC_8X8_UNORM        DXGI_FORMAT(162)
#define DXGI_FORMAT_ASTC_8X8_UNORM_SRGB   DXGI_FORMAT(163)
#define DXGI_FORMAT_ASTC_10X5_TYPELESS    DXGI_FORMAT(165)
#define DXGI_FORMAT_ASTC_10X5_UNORM       DXGI_FORMAT(166)
#define DXGI_FORMAT_ASTC_10X5_UNORM_SRGB  DXGI_FORMAT(167)
#define DXGI_FORMAT_ASTC_10X6_TYPELESS    DXGI_FORMAT(169)
#define DXGI_FORMAT_ASTC_10X6_UNORM       DXGI_FORMAT(170)
#define DXGI_FORMAT_ASTC_10X6_UNORM_SRGB  DXGI_FORMAT(171)
#define DXGI_FORMAT_ASTC_10X8_TYPELESS    DXGI_FORMAT(173)
#define DXGI_FORMAT_ASTC_10X8_UNORM       DXGI_FORMAT(174)
#define DXGI_FORMAT_ASTC_10X8_UNORM_SRGB  DXGI_FORMAT(175)
#define DXGI_FORMAT_ASTC_10X10_TYPELESS   DXGI_FORMAT(177)
#define DXGI_FORMAT_ASTC_10X10_UNORM      DXGI_FORMAT(178)
#define DXGI_FORMAT_ASTC_10X10_UNORM_SRGB DXGI_FORMAT(179)
#define DXGI_FORMAT_ASTC_12X10_TYPELESS   DXGI_FORMAT(181)
#define DXGI_FORMAT_ASTC_12X10_UNORM      DXGI_FORMAT(182)
#define DXGI_FORMAT_ASTC_12X10_UNORM_SRGB DXGI_FORMAT(183)
#define DXGI_FORMAT_ASTC_12X12_TYPELESS   DXGI_FORMAT(185)
#define DXGI_FORMAT_ASTC_12X12_UNORM      DXGI_FORMAT(186)
#define DXGI_FORMAT_ASTC_12X12_UNORM_SRGB DXGI_FORMAT(187)

	inline DXGI_FORMAT FormatToDXFormat(EPixelFormat pixel_fmt)
	{
		switch (pixel_fmt)
		{
		case PXF_UNKNOWN:
			return DXGI_FORMAT_UNKNOWN;
		case PXF_R16_FLOAT:
			return DXGI_FORMAT_R16_FLOAT;
		case PXF_R16_UINT:
			return DXGI_FORMAT_R16_UINT;
		case PXF_R16_SINT:
			return DXGI_FORMAT_R16_SINT;
		case PXF_R16_UNORM:
			return DXGI_FORMAT_R16_UNORM;
		case PXF_R16_SNORM:
			return DXGI_FORMAT_R16_SNORM;
		case PXF_R32_UINT:
			return DXGI_FORMAT_R32_UINT;
		case PXF_R32_SINT:
			return DXGI_FORMAT_R32_SINT;
		case PXF_R32_FLOAT:
			return DXGI_FORMAT_R32_FLOAT;
		case PXF_R8G8B8A8_SINT:
			return DXGI_FORMAT_R8G8B8A8_SINT;
		case PXF_R8G8B8A8_UINT:
			return DXGI_FORMAT_R8G8B8A8_UINT;
		case PXF_R8G8B8A8_UNORM:
			return DXGI_FORMAT_R8G8B8A8_UNORM;
		case PXF_R8G8B8A8_SNORM:
			return DXGI_FORMAT_R8G8B8A8_SNORM;
		case PXF_R16G16_UINT:
			return DXGI_FORMAT_R16G16_UINT;
		case PXF_R16G16_SINT:
			return DXGI_FORMAT_R16G16_SINT;
		case PXF_R16G16_FLOAT:
			return DXGI_FORMAT_R16G16_FLOAT;
		case PXF_R16G16_UNORM:
			return DXGI_FORMAT_R16G16_UNORM;
		case PXF_R16G16_SNORM:
			return DXGI_FORMAT_R16G16_SNORM;
		case PXF_R16G16B16A16_UINT:
			return DXGI_FORMAT_R16G16B16A16_UINT;
		case PXF_R16G16B16A16_SINT:
			return DXGI_FORMAT_R16G16B16A16_SINT;
		case PXF_R16G16B16A16_FLOAT:
			return DXGI_FORMAT_R16G16B16A16_FLOAT;
		case PXF_R16G16B16A16_UNORM:
			return DXGI_FORMAT_R16G16B16A16_UNORM;
		case PXF_R16G16B16A16_SNORM:
			return DXGI_FORMAT_R16G16B16A16_SNORM;
		case PXF_R32G32B32A32_UINT:
			return DXGI_FORMAT_R32G32B32A32_UINT;
		case PXF_R32G32B32A32_SINT:
			return DXGI_FORMAT_R32G32B32A32_SINT;
		case PXF_R32G32B32A32_FLOAT:
			return DXGI_FORMAT_R32G32B32A32_FLOAT;
		case PXF_R32G32B32_UINT:
			return DXGI_FORMAT_R32G32B32_UINT;
		case PXF_R32G32B32_SINT:
			return DXGI_FORMAT_R32G32B32_SINT;
		case PXF_R32G32B32_FLOAT:
			return DXGI_FORMAT_R32G32B32_FLOAT;
		case PXF_R32G32_UINT:
			return DXGI_FORMAT_R32G32_UINT;
		case PXF_R32G32_SINT:
			return DXGI_FORMAT_R32G32_SINT;
		case PXF_R32G32_FLOAT:
			return DXGI_FORMAT_R32G32_FLOAT;
		case PXF_D24_UNORM_S8_UINT:
			return DXGI_FORMAT_D24_UNORM_S8_UINT;
		case PXF_D32_FLOAT:
			return DXGI_FORMAT_D32_FLOAT;
		case PXF_D32_FLOAT_S8X24_UINT:
			return DXGI_FORMAT_D32_FLOAT_S8X24_UINT;
		case PXF_D16_UNORM:
			return DXGI_FORMAT_D16_UNORM;
		case PXF_B8G8R8A8_UNORM:
			return DXGI_FORMAT_B8G8R8A8_UNORM;
		case PXF_R11G11B10_FLOAT:
			return DXGI_FORMAT_R11G11B10_FLOAT;
		case PXF_R8G8_UNORM:
			return DXGI_FORMAT_R8G8_UNORM;
		case PXF_R8_UNORM:
			return DXGI_FORMAT_R8_UNORM;
		case PXF_R32_TYPELESS:
			return DXGI_FORMAT_R32_TYPELESS;
		case PXF_R32G32B32A32_TYPELESS:
			return DXGI_FORMAT_R32G32B32A32_TYPELESS;
		case PXF_R32G32B32_TYPELESS:
			return DXGI_FORMAT_R32G32B32_TYPELESS;
		case PXF_R16G16B16A16_TYPELESS:
			return DXGI_FORMAT_R16G16B16A16_TYPELESS;
		case PXF_R32G32_TYPELESS:
			return DXGI_FORMAT_R32G32_TYPELESS;
		case PXF_R32G8X24_TYPELESS:
			return DXGI_FORMAT_R32G8X24_TYPELESS;
		case PXF_R10G10B10A2_TYPELESS:
			return DXGI_FORMAT_R10G10B10A2_TYPELESS;
		case PXF_R10G10B10A2_UNORM:
			return DXGI_FORMAT_R10G10B10A2_UNORM;
		case PXF_R10G10B10A2_UNORM_SRGB:
			break;
		case PXF_R10G10B10A2_SNORM:
			break;
		case PXF_R10G10B10A2_UINT:
			return DXGI_FORMAT_R10G10B10A2_UINT;
		case PXF_R10G10B10A2_SINT:
			break;
		case PXF_B10G10R10A2_TYPELESS:
			break;
		case PXF_B10G10R10A2_UNORM:
			break;
		case PXF_B10G10R10A2_UNORM_SRGB:
			break;
		case PXF_B10G10R10A2_SNORM:
			break;
		case PXF_B10G10R10A2_UINT:
			break;
		case PXF_B10G10R10A2_SINT:
			break;
		case PXF_R8G8B8A8_TYPELESS:
			return DXGI_FORMAT_R8G8B8A8_TYPELESS;
		case PXF_R8G8B8A8_UNORM_SRGB:
			return DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
		case PXF_R16G16_TYPELESS:
			return DXGI_FORMAT_R16G16_TYPELESS;
		case PXF_R24G8_TYPELESS:
			return DXGI_FORMAT_R24G8_TYPELESS;
		case PXF_R24_UNORM_X8_TYPELESS:
			return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
		case PXF_X24_TYPELESS_G8_UINT:
			return DXGI_FORMAT_X24_TYPELESS_G8_UINT;
		case PXF_R8G8_TYPELESS:
			return DXGI_FORMAT_R8G8_TYPELESS;
		case PXF_R8G8_UINT:
			return DXGI_FORMAT_R8G8_UINT;
		case PXF_R8G8_SNORM:
			return DXGI_FORMAT_R8G8_SNORM;
		case PXF_R8G8_SINT:
			return DXGI_FORMAT_R8G8_SINT;
		case PXF_R16_TYPELESS:
			return DXGI_FORMAT_R16_TYPELESS;
		case PXF_R8_TYPELESS:
			return DXGI_FORMAT_R8_TYPELESS;
		case PXF_R8_UINT:
			return DXGI_FORMAT_R8_UINT;
		case PXF_R8_SNORM:
			return DXGI_FORMAT_R8_SNORM;
		case PXF_R8_SINT:
			return DXGI_FORMAT_R8_SINT;
		case PXF_A8_UNORM:
			return DXGI_FORMAT_A8_UNORM;
		case PXF_B8G8R8X8_UNORM:
			return DXGI_FORMAT_B8G8R8X8_UNORM;
		case PXF_B8G8R8A8_TYPELESS:
			return DXGI_FORMAT_B8G8R8A8_TYPELESS;
		case PXF_B8G8R8A8_UNORM_SRGB:
			return DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
		case PXF_B8G8R8A8_SNORM:
			break;
		case PXF_B8G8R8A8_UINT:
			break;
		case PXF_B8G8R8A8_SINT:
			break;
		case PXF_B8G8R8X8_TYPELESS:
			return DXGI_FORMAT_B8G8R8X8_TYPELESS;
		case PXF_B8G8R8X8_UNORM_SRGB:
			return DXGI_FORMAT_B8G8R8X8_UNORM_SRGB;
		case PXF_B5G6R5_UNORM:
			return DXGI_FORMAT_B5G6R5_UNORM;
		case PXF_B4G4R4A4_UNORM:
			return DXGI_FORMAT_B4G4R4A4_UNORM;
		case PXF_BC1_TYPELESS:
			return DXGI_FORMAT_BC1_TYPELESS;
		case PXF_BC1_UNORM:
			return DXGI_FORMAT_BC1_UNORM;
		case PXF_BC1_UNORM_SRGB:
			return DXGI_FORMAT_BC1_UNORM_SRGB;
		case PXF_BC2_TYPELESS:
			return DXGI_FORMAT_BC2_TYPELESS;
		case PXF_BC2_UNORM:
			return DXGI_FORMAT_BC2_UNORM;
		case PXF_BC2_UNORM_SRGB:
			return DXGI_FORMAT_BC2_UNORM_SRGB;
		case PXF_BC3_TYPELESS:
			return DXGI_FORMAT_BC3_TYPELESS;
		case PXF_BC3_UNORM:
			return DXGI_FORMAT_BC3_UNORM;
		case PXF_BC3_UNORM_SRGB:
			return DXGI_FORMAT_BC3_UNORM_SRGB;
		case PXF_BC4_TYPELESS:
			return DXGI_FORMAT_BC4_TYPELESS;
		case PXF_BC4_UNORM:
			return DXGI_FORMAT_BC4_UNORM;
		case PXF_BC4_SNORM:
			return DXGI_FORMAT_BC4_SNORM;
		case PXF_BC5_TYPELESS:
			return DXGI_FORMAT_BC5_TYPELESS;
		case PXF_BC5_UNORM:
			return DXGI_FORMAT_BC5_UNORM;
		case PXF_BC5_SNORM:
			return DXGI_FORMAT_BC5_SNORM;
		case PXF_BC6H_TYPELESS:
			return DXGI_FORMAT_BC6H_TYPELESS;
		case PXF_BC6H_UF16:
			return DXGI_FORMAT_BC6H_UF16;
		case PXF_BC6H_SF16:
			return DXGI_FORMAT_BC6H_SF16;
		case PXF_BC7_TYPELESS:
			return DXGI_FORMAT_BC7_TYPELESS;
		case PXF_BC7_UNORM:
			return DXGI_FORMAT_BC7_UNORM;
		case PXF_BC7_UNORM_SRGB:
			return DXGI_FORMAT_BC7_UNORM_SRGB;

		case PXF_ETC2_RGB8:
		case PXF_ETC2_SRGB8:
		case PXF_ETC2_RGBA8:
		case PXF_ETC2_SRGBA8:
		case PXF_ETC2_R11:
		case PXF_ETC2_SIGNED_R11:
		case PXF_ETC2_RG11:
		case PXF_ETC2_SIGNED_RG11:
		case PXF_ETC2_RGBA1:
		case PXF_ETC2_SRGBA1:
		default:
			break;
		}
		return DXGI_FORMAT_UNKNOWN;
	}
	inline EPixelFormat DXFormatToFormat(DXGI_FORMAT format)
	{
		switch (format)
		{
			case DXGI_FORMAT_UNKNOWN:
				return PXF_UNKNOWN;
			case DXGI_FORMAT_R32G32B32A32_TYPELESS:
				return PXF_R32G32B32A32_TYPELESS;
			case DXGI_FORMAT_R32G32B32A32_FLOAT:
				return PXF_R32G32B32A32_FLOAT;
			case DXGI_FORMAT_R32G32B32A32_UINT:
				return PXF_R32G32B32A32_UINT;
			case DXGI_FORMAT_R32G32B32A32_SINT:
				return PXF_R32G32B32A32_SINT;
			case DXGI_FORMAT_R32G32B32_TYPELESS:
				return PXF_R32G32B32_TYPELESS;
			case DXGI_FORMAT_R32G32B32_FLOAT:
				return PXF_R32G32B32_FLOAT;
			case DXGI_FORMAT_R32G32B32_UINT:
				return PXF_R32G32B32_UINT;
			case DXGI_FORMAT_R32G32B32_SINT:
				return PXF_R32G32B32_SINT;
			case DXGI_FORMAT_R16G16B16A16_TYPELESS:
				return PXF_R16G16B16A16_TYPELESS;
			case DXGI_FORMAT_R16G16B16A16_FLOAT:
				return PXF_R16G16B16A16_FLOAT;
			case DXGI_FORMAT_R16G16B16A16_UNORM:
				return PXF_R16G16B16A16_UNORM;
			case DXGI_FORMAT_R16G16B16A16_UINT:
				return PXF_R16G16B16A16_UINT;
			case DXGI_FORMAT_R16G16B16A16_SNORM:
				return PXF_R16G16B16A16_SNORM;
			case DXGI_FORMAT_R16G16B16A16_SINT:
				return PXF_R16G16B16A16_SINT;
			case DXGI_FORMAT_R32G32_TYPELESS:
				return PXF_R32G32_TYPELESS;
			case DXGI_FORMAT_R32G32_FLOAT:
				return PXF_R32G32_FLOAT;
			case DXGI_FORMAT_R32G32_UINT:
				return PXF_R32G32_UINT;
			case DXGI_FORMAT_R32G32_SINT:
				return PXF_R32G32_SINT;
			case DXGI_FORMAT_R32G8X24_TYPELESS:
				return PXF_R32G8X24_TYPELESS;
			case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
				return PXF_D32_FLOAT_S8X24_UINT;
			/*case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
				return PXF_R32_FLOAT_X8X24_TYPELESS;
			case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
				break;*/
			case DXGI_FORMAT_R10G10B10A2_TYPELESS:
				return PXF_R10G10B10A2_TYPELESS;
			case DXGI_FORMAT_R10G10B10A2_UNORM:
				return PXF_R10G10B10A2_UNORM;
			case DXGI_FORMAT_R10G10B10A2_UINT:
				return PXF_R10G10B10A2_UINT;
			case DXGI_FORMAT_R11G11B10_FLOAT:
				return PXF_R11G11B10_FLOAT;
			case DXGI_FORMAT_R8G8B8A8_TYPELESS:
				return PXF_R8G8B8A8_TYPELESS;
			case DXGI_FORMAT_R8G8B8A8_UNORM:
				return PXF_R8G8B8A8_UNORM;
			case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
				return PXF_R8G8B8A8_UNORM_SRGB;
			case DXGI_FORMAT_R8G8B8A8_UINT:
				return PXF_R8G8B8A8_UINT;
			case DXGI_FORMAT_R8G8B8A8_SNORM:
				return PXF_R8G8B8A8_SNORM;
			case DXGI_FORMAT_R8G8B8A8_SINT:
				return PXF_R8G8B8A8_SINT;
			case DXGI_FORMAT_R16G16_TYPELESS:
				return PXF_R16G16_TYPELESS;
			case DXGI_FORMAT_R16G16_FLOAT:
				return PXF_R16G16_FLOAT;
			case DXGI_FORMAT_R16G16_UNORM:
				return PXF_R16G16_UNORM;
			case DXGI_FORMAT_R16G16_UINT:
				return PXF_R16G16_UINT;
			case DXGI_FORMAT_R16G16_SNORM:
				return PXF_R16G16_SNORM;
			case DXGI_FORMAT_R16G16_SINT:
				return PXF_R16G16_SINT;
			case DXGI_FORMAT_R32_TYPELESS:
				return PXF_R32_TYPELESS;
			case DXGI_FORMAT_D32_FLOAT:
				return PXF_D32_FLOAT;
			case DXGI_FORMAT_R32_FLOAT:
				return PXF_R32_FLOAT;
			case DXGI_FORMAT_R32_UINT:
				return PXF_R32_UINT;
			case DXGI_FORMAT_R32_SINT:
				return PXF_R32_SINT;
			case DXGI_FORMAT_R24G8_TYPELESS:
				return PXF_R24G8_TYPELESS;
			case DXGI_FORMAT_D24_UNORM_S8_UINT:
				return PXF_D24_UNORM_S8_UINT;
			case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
				return PXF_R24_UNORM_X8_TYPELESS;
			case DXGI_FORMAT_X24_TYPELESS_G8_UINT:
				return PXF_X24_TYPELESS_G8_UINT;
			case DXGI_FORMAT_R8G8_TYPELESS:
				return PXF_R8G8_TYPELESS;
			case DXGI_FORMAT_R8G8_UNORM:
				return PXF_R8G8_UNORM;
			case DXGI_FORMAT_R8G8_UINT:
				return PXF_R8G8_UINT;
			case DXGI_FORMAT_R8G8_SNORM:
				return PXF_R8G8_SNORM;
			case DXGI_FORMAT_R8G8_SINT:
				return PXF_R8G8_SINT;
			case DXGI_FORMAT_R16_TYPELESS:
				return PXF_R16_TYPELESS;
			case DXGI_FORMAT_R16_FLOAT:
				return PXF_R16_FLOAT;
			case DXGI_FORMAT_D16_UNORM:
				return PXF_D16_UNORM;
			case DXGI_FORMAT_R16_UNORM:
				return PXF_R16_UNORM;
			case DXGI_FORMAT_R16_UINT:
				return PXF_R16_UINT;
			case DXGI_FORMAT_R16_SNORM:
				return PXF_R16_SNORM;
			case DXGI_FORMAT_R16_SINT:
				return PXF_R16_SINT;
			case DXGI_FORMAT_R8_TYPELESS:
				return PXF_R8_TYPELESS;
			case DXGI_FORMAT_R8_UNORM:
				return PXF_R8_UNORM;
			case DXGI_FORMAT_R8_UINT:
				return PXF_R8_UINT;
			case DXGI_FORMAT_R8_SNORM:
				return PXF_R8_SNORM;
			case DXGI_FORMAT_R8_SINT:
				return PXF_R8_SINT;
			case DXGI_FORMAT_A8_UNORM:
				return PXF_A8_UNORM;
			/*case DXGI_FORMAT_R1_UNORM:
				return PXF_R1_UNORM;
			case DXGI_FORMAT_R9G9B9E5_SHAREDEXP:
				break;
			case DXGI_FORMAT_R8G8_B8G8_UNORM:
				return PXF_R8G8_B8G8_UNORM;
			case DXGI_FORMAT_G8R8_G8B8_UNORM:
				break;
			case DXGI_FORMAT_BC1_TYPELESS:
				break;
			case DXGI_FORMAT_BC1_UNORM:
				break;
			case DXGI_FORMAT_BC1_UNORM_SRGB:
				break;
			case DXGI_FORMAT_BC2_TYPELESS:
				break;
			case DXGI_FORMAT_BC2_UNORM:
				break;
			case DXGI_FORMAT_BC2_UNORM_SRGB:
				break;
			case DXGI_FORMAT_BC3_TYPELESS:
				break;
			case DXGI_FORMAT_BC3_UNORM:
				break;
			case DXGI_FORMAT_BC3_UNORM_SRGB:
				break;
			case DXGI_FORMAT_BC4_TYPELESS:
				break;
			case DXGI_FORMAT_BC4_UNORM:
				break;
			case DXGI_FORMAT_BC4_SNORM:
				break;
			case DXGI_FORMAT_BC5_TYPELESS:
				break;
			case DXGI_FORMAT_BC5_UNORM:
				break;
			case DXGI_FORMAT_BC5_SNORM:
				break;
			case DXGI_FORMAT_B5G6R5_UNORM:
				break;
			case DXGI_FORMAT_B5G5R5A1_UNORM:
				break;
			case DXGI_FORMAT_B8G8R8A8_UNORM:
				break;
			case DXGI_FORMAT_B8G8R8X8_UNORM:
				break;
			case DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
				break;
			case DXGI_FORMAT_B8G8R8A8_TYPELESS:
				break;
			case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
				break;
			case DXGI_FORMAT_B8G8R8X8_TYPELESS:
				break;
			case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB:
				break;
			case DXGI_FORMAT_BC6H_TYPELESS:
				break;
			case DXGI_FORMAT_BC6H_UF16:
				break;
			case DXGI_FORMAT_BC6H_SF16:
				break;
			case DXGI_FORMAT_BC7_TYPELESS:
				break;
			case DXGI_FORMAT_BC7_UNORM:
				break;
			case DXGI_FORMAT_BC7_UNORM_SRGB:
				break;
			case DXGI_FORMAT_AYUV:
				break;
			case DXGI_FORMAT_Y410:
				break;
			case DXGI_FORMAT_Y416:
				break;
			case DXGI_FORMAT_NV12:
				break;
			case DXGI_FORMAT_P010:
				break;
			case DXGI_FORMAT_P016:
				break;
			case DXGI_FORMAT_420_OPAQUE:
				break;
			case DXGI_FORMAT_YUY2:
				break;
			case DXGI_FORMAT_Y210:
				break;
			case DXGI_FORMAT_Y216:
				break;
			case DXGI_FORMAT_NV11:
				break;
			case DXGI_FORMAT_AI44:
				break;
			case DXGI_FORMAT_IA44:
				break;
			case DXGI_FORMAT_P8:
				break;
			case DXGI_FORMAT_A8P8:
				break;
			case DXGI_FORMAT_B4G4R4A4_UNORM:
				break;
			case DXGI_FORMAT_P208:
				break;
			case DXGI_FORMAT_V208:
				break;
			case DXGI_FORMAT_V408:
				break;
			case DXGI_FORMAT_SAMPLER_FEEDBACK_MIN_MIP_OPAQUE:
				break;
			case DXGI_FORMAT_SAMPLER_FEEDBACK_MIP_REGION_USED_OPAQUE:
				break;
			case DXGI_FORMAT_FORCE_UINT:
				break;*/
			default:
				return PXF_UNKNOWN;
		}
	}
}

NS_END