<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>$(SolutionDir)\binaries\Plugins</BaseOutputPath>
  </PropertyGroup>

  <Import Project="..\Survivor.projitems" Label="Shared" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Module\Engine.Window\Engine.Window.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="$(SolutionDir)CS_Rpc_AutoSync.bat" />
  </Target>

</Project>
