#ifndef	_PGC_EROSION_INCWATER_H_
#define _PGC_EROSION_INCWATER_H_

RWTexture2D<float> WaterTexture;
/**Meta Begin:(CS_IncWaterMain)
HLSL=2021
Meta End:(CS_IncWaterMain)**/
[numthreads(DispatchX, DispatchY, DispatchZ)]
void CS_IncWaterMain(uint3 DispatchThreadId : SV_DispatchThreadID, uint3 LocalThreadId : SV_GroupThreadID, uint3 GroupId : SV_GroupID)
{
    WaterTexture[DispatchThreadId.xy].r += 0.1f;
}

#endif//_PGC_EROSION_INCWATER_H_