<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup Label="UserMacros">
		<TtPluginName>$(MSBuildProjectName.Split('.')[0])</TtPluginName>
		<TtPluginSourceRoot>$(ProjectDir)..\</TtPluginSourceRoot>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="del $(TtOutputBasePath) /q" />
		<Exec Command="copy $(TtPluginSourceRoot)$(TtPluginName).plugin $(TtOutputBasePath)..\$(TtPluginName).plugin" />
	</Target>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="rename $(TtOutputBasePath)*.pdb *.tpdb" />
		<Exec Command="del $(TtIntermediateBasePath)$(MSBuildProjectName)\*.pdb /s /q" />
	</Target>
</Project>