//generated from legacy CppWeaving ImGui surface; native entrypoints routed through TitanImGuiBridge
using System;
using System.Runtime.InteropServices;


[System.Flags]
public enum ImGuiCol_
{
	ImGuiCol_Text = 0,
	ImGuiCol_TextDisabled = 1,
	ImGuiCol_WindowBg = 2,
	ImGuiCol_ChildBg = 3,
	ImGuiCol_PopupBg = 4,
	ImGuiCol_Border = 5,
	ImGuiCol_BorderShadow = 6,
	ImGuiCol_FrameBg = 7,
	ImGuiCol_FrameBgHovered = 8,
	ImGuiCol_FrameBgActive = 9,
	ImGuiCol_TitleBg = 10,
	ImGuiCol_TitleBgActive = 11,
	ImGuiCol_TitleBgCollapsed = 12,
	ImGuiCol_MenuBarBg = 13,
	ImGuiCol_ScrollbarBg = 14,
	ImGuiCol_ScrollbarGrab = 15,
	ImGuiCol_ScrollbarGrabHovered = 16,
	ImGuiCol_ScrollbarGrabActive = 17,
	ImGuiCol_CheckMark = 18,
	ImGuiCol_SliderGrab = 19,
	ImGuiCol_SliderGrabActive = 20,
	ImGuiCol_Button = 21,
	ImGuiCol_ButtonHovered = 22,
	ImGuiCol_ButtonActive = 23,
	ImGuiCol_Header = 24,
	ImGuiCol_HeaderHovered = 25,
	ImGuiCol_HeaderActive = 26,
	ImGuiCol_Separator = 27,
	ImGuiCol_SeparatorHovered = 28,
	ImGuiCol_SeparatorActive = 29,
	ImGuiCol_ResizeGrip = 30,
	ImGuiCol_ResizeGripHovered = 31,
	ImGuiCol_ResizeGripActive = 32,
	ImGuiCol_InputTextCursor = 33,
	ImGuiCol_TabHovered = 34,
	ImGuiCol_Tab = 35,
	ImGuiCol_TabSelected = 36,
	ImGuiCol_TabSelectedOverline = 37,
	ImGuiCol_TabDimmed = 38,
	ImGuiCol_TabDimmedSelected = 39,
	ImGuiCol_TabDimmedSelectedOverline = 40,
	ImGuiCol_DockingPreview = 41,
	ImGuiCol_DockingEmptyBg = 42,
	ImGuiCol_PlotLines = 43,
	ImGuiCol_PlotLinesHovered = 44,
	ImGuiCol_PlotHistogram = 45,
	ImGuiCol_PlotHistogramHovered = 46,
	ImGuiCol_TableHeaderBg = 47,
	ImGuiCol_TableBorderStrong = 48,
	ImGuiCol_TableBorderLight = 49,
	ImGuiCol_TableRowBg = 50,
	ImGuiCol_TableRowBgAlt = 51,
	ImGuiCol_TextLink = 52,
	ImGuiCol_TextSelectedBg = 53,
	ImGuiCol_TreeLines = 54,
	ImGuiCol_DragDropTarget = 55,
	ImGuiCol_DragDropTargetBg = 56,
	ImGuiCol_UnsavedMarker = 57,
	ImGuiCol_NavCursor = 58,
	ImGuiCol_NavWindowingHighlight = 59,
	ImGuiCol_NavWindowingDimBg = 60,
	ImGuiCol_ModalWindowDimBg = 61,
	ImGuiCol_COUNT = 62,
	ImGuiCol_TabActive = 36,
	ImGuiCol_TabUnfocused = 38,
	ImGuiCol_TabUnfocusedActive = 39,
	ImGuiCol_NavHighlight = 58,
}
