#pragma once

#if !defined(__REF_CLANG__)
//todo: generated by tools
namespace NxMath
{
	template<>
	struct NxConstValue<0.0, NxInt64, 24>
	{
		static const NxInt64 _ResultValue = 0;
		static constexpr const NxInt64 ResultValue(double dummy = 0)
		{
			return _ResultValue;
		}
	};
}

#endif