<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\binaries\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>$(DefineConstants);PWindow;TRACE;TitanEngine_AutoGen_RPC;TitanEngine_AutoGen_Macross</DefineConstants>
    <SkipPostSharp>True</SkipPostSharp>
    <NoWarn>1701;1702;1998;8632</NoWarn>
    <DebugType>full</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\binaries\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DefineConstants>$(DefineConstants);PWindow;TRACE;TitanEngine_AutoGen_RPC;TitanEngine_AutoGen_Macross</DefineConstants>
    <NoWarn>1701;1702;1998;8632</NoWarn>
    <DebugType>full</DebugType>
    <Optimize>True</Optimize>
	<DebugSymbols>true</DebugSymbols>
	<IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <Import Project="..\..\CSharpCode\Base\Base.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\CodeBuilder\CodeBuilder.projitems" Label="Shared" />

  <Import Project="..\..\codegen\NativeBinder\CodeGenCSharp.projitems" Label="Shared" />

  <Import Project="..\..\codegen\Cs2Cpp\cs\Cs2Cpp.projitems" Label="Shared" />

  <Import Project="..\..\codegen\Macross\Engine\EngineMacross.projitems" Label="Shared" />

  <Import Project="..\..\codegen\Serializer\Engine\EngineSerializer.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Editor\Editor.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\GamePlay\GamePlay.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\ImGui\ImGui.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Math\Math.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Grapics\Mesh\Mesh.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Grapics\Pipeline\Pipeline.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\Procedure\Procedure.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Rtti\Rtti.projitems" Label="Shared" />

  <Import Project="..\..\3rd\csharp\StbImageSharp\StbImageSharp.projitems" Label="Shared" />

  <Import Project="..\..\3rd\csharp\StbImageWriteSharp\StbImageWriteSharp.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Platform\Windows\Windows.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\DataSet\DataSet.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\AssemblyLoader\AssemblyLoader.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\CSScripting\CSScripting.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\FBX\FBX.projitems" Label="Shared" />

  <Import Project="..\..\CSharpCode\Bricks\Network\Network.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Animation\Animation.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\CodeCompiler\CodeCompiler.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\WorldSimulator\WorldSimulator.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\TcpServer\TcpServer.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\SourceControl\SourceControl.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\VXGI\VXGI.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\PhysicsCore\PhysicsCore.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\ProjectGen\ProjectGen.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Terrain\Terrain.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Input\Input.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\VirtualTexture\VirtualTexture.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Particle\Particle.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\RenderPolicyEditor\RenderPolicyEditor.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\NodeGraph\NodeGraph.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\StateMachine\StateMachine.projitems" Label="Shared" />
  <Import Project="..\..\3rd\csharp\NvTriStrip\NvTriStrip.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\NxRHI\NxRHI.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\WindowSDL\WindowSDL.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\BehaviorTree\BehaviorTree.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\DesignMacross\DesignMacross.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Recast\Recast.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\UI\UI.projitems" Label="Shared" />
  <Import Project="..\..\3rd\csharp\xxHash\xxHash.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Collision\Collision.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\ImageDecoder\ImageDecoder.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\GpuDriven\GpuDriven.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Font\Font.projitems" Label="Shared" />
  <Import Project="..\..\3rd\csharp\AstcDecoder\AstcDecoder.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\PythonRuntime\PythonRuntime.projitems" Label="Shared" />
  <Import Project="..\..\3rd\csharp\JitherOpenEXR\JitherOpenEXR.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\VirtualShadowMaps\VirtualShadowMaps.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\DestinyPX\NxMath\NxMath.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\DestinyPX\NxPhysics\NxPhysics.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\AssetImpExp\AssetImpExp.projitems" Label="Shared" />
  <Import Project="..\..\3rd\csharp\AssimpNet\AssimpNet.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\CompilingGenerator\CompilingGenerator.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Localization\Localization.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\DistanceField\DistanceField.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\AdvanceShadow\AdvanceShadow.projitems" Label="Shared" />
  <Import Project="..\..\3rd\csharp\Sprache\Sprache.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\FX\Hair\Hair.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\FX\Skin\Skin.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\DataCopyer\DataCopyer.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\AIGC\AIGC.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\DevIDE\DevIDE.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\GI\PRT\PRT.projitems" Label="Shared" />
  <Import Project="..\..\CSharpCode\Bricks\Meshly\Meshly.projitems" Label="Shared" />
  <ItemGroup>
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\cs\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\de\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\es\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\fr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\it\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\ja\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\ko\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\Microsoft.Bcl.AsyncInterfaces.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\Microsoft.Build.Locator.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\Newtonsoft.Json.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\pl\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\pt-BR\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\ru\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Buffers.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Collections.Immutable.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.CommandLine.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Memory.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Numerics.Vectors.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Runtime.CompilerServices.Unsafe.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Text.Encodings.Web.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Text.Json.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.Threading.Tasks.Extensions.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\System.ValueTuple.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\tr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\zh-Hans\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-net472\zh-Hant\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\cs\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\de\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\es\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\fr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\it\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\ja\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\ko\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\Microsoft.Build.Locator.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll.config" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\Newtonsoft.Json.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\pl\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\pt-BR\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\runtimes\browser\lib\net6.0\System.Text.Encodings.Web.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\ru\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\System.Collections.Immutable.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\System.CommandLine.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\System.Text.Encodings.Web.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\System.Text.Json.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\tr\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\zh-Hans\System.CommandLine.resources.dll" />
    <Content Remove="C:\Users\johnsonsong\.nuget\packages\microsoft.codeanalysis.workspaces.msbuild\4.11.0\contentFiles\any\any\BuildHost-netcore\zh-Hant\System.CommandLine.resources.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.1.0" />
    <PackageReference Include="MemoryInterop.ILPatcher" Version="2.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.13.0" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="NLua" Version="1.7.6" />
    <PackageReference Include="NPOI" Version="2.7.2" />
    <PackageReference Include="ppy.SDL3-CS" Version="2025.703.0" />
    <PackageReference Include="RIPEMD160" Version="1.0.1" />
    <PackageReference Include="System.CodeDom" Version="9.0.0" />
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="$(SolutionDir)CS_Engine.bat" />
  </Target>
  
  <ItemGroup>
    <ProjectReference Include="..\CompilingGenerator\CompilingGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  
  <PropertyGroup>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

</Project>
