using System;
using System.Collections.Generic;
using System.ComponentModel;
using EngineNS.Bricks.NodeGraph;
using EngineNS.GamePlay.Scene;

namespace EngineNS.Bricks.Procedure.Node
{
    public enum ESurfaceProjectionMissPolicy
    {
        KeepOriginal,
        Drop,
    }

    /// <summary>
    /// 沿指定世界空间方向将点投影到场景碰撞表面。
    /// </summary>
    [Bricks.CodeBuilder.ContextMenu("Surface Projection", "Sampling\\Surface Projection", TtPgcGraph.PgcEditorKeyword)]
    [Rtti.Meta("")]
    public partial class TtSurfaceProjectionNode : TtPgcNodeBase
    {
        [Browsable(false)]
        public PinIn PointsPin { get; set; } = new PinIn();
        [Browsable(false)]
        public PinOut ProjectedPointsPin { get; set; } = new PinOut();
        [Browsable(false)]
        public PinOut NormalsPin { get; set; } = new PinOut();
        [Browsable(false)]
        public PinOut HitDistancesPin { get; set; } = new PinOut();
        [Browsable(false)]
        public PinOut HitMaskPin { get; set; } = new PinOut();
        [Browsable(false)]
        public PinOut SourceIndicesPin { get; set; } = new PinOut();

        public TtBufferCreator Vector3Desc { get; } =
            TtBufferCreator.CreateInstance<TtSuperBuffer<Vector3, FFloat3Operator>>(-1, 1, 1);
        public TtBufferCreator FloatDesc { get; } =
            TtBufferCreator.CreateInstance<TtSuperBuffer<float, FFloatOperator>>(-1, 1, 1);
        public TtBufferCreator MaskDesc { get; } =
            TtBufferCreator.CreateInstance<TtSuperBuffer<sbyte, FSByteOperator>>(-1, 1, 1);
        public TtBufferCreator IntDesc { get; } =
            TtBufferCreator.CreateInstance<TtSuperBuffer<int, FIntOperator>>(-1, 1, 1);

        [Rtti.Meta("")]
        [Category("Projection")]
        [Description("World-space projection direction")]
        public Vector3 Direction { get; set; } = Vector3.Down;

        [Rtti.Meta("")]
        [Category("Projection")]
        [Description("Maximum projection distance in metres, measured from each input point")]
        public float MaxDistance { get; set; } = 1000.0f;

        [Rtti.Meta("")]
        [Category("Projection")]
        [Description("Distance in metres to offset the ray start opposite the projection direction")]
        public float StartOffset { get; set; } = 0.1f;

        [Rtti.Meta("")]
        [Category("Projection")]
        public ESurfaceProjectionMissPolicy MissPolicy { get; set; } =
            ESurfaceProjectionMissPolicy.KeepOriginal;

        [Rtti.Meta("")]
        [Category("Projection")]
        [Description("Ignore scene nodes generated by the host PGC Volume during its previous run")]
        public bool IgnoreGeneratedNodes { get; set; } = true;

        [Browsable(false)]
        public string LastDiagnostic { get; private set; }

        public TtSurfaceProjectionNode()
        {
            Icon.Size = new Vector2(25, 25);
            Icon.Color = 0xFFFFA040;
            TitleColor = 0xFF604020;
            BackColor = 0x80808080;

            AddInput(PointsPin, "Points", Vector3Desc);
            AddOutput(ProjectedPointsPin, "Projected Points", Vector3Desc);
            AddOutput(NormalsPin, "Normals", Vector3Desc);
            AddOutput(HitDistancesPin, "Hit Distances", FloatDesc);
            AddOutput(HitMaskPin, "Hit Mask", MaskDesc);
            AddOutput(SourceIndicesPin, "Source Indices", IntDesc);
        }

        public override TtBufferCreator GetOutBufferCreator(PinOut pin)
        {
            var graph = ParentGraph as TtPgcGraph;
            var points = graph?.ResolveInput(PointsPin);
            if (points != null)
            {
                Vector3Desc.SetSize(points.BufferCreator);
                FloatDesc.SetSize(points.BufferCreator);
                MaskDesc.SetSize(points.BufferCreator);
                IntDesc.SetSize(points.BufferCreator);
            }

            if (pin == ProjectedPointsPin || pin == NormalsPin)
                return Vector3Desc;
            if (pin == HitDistancesPin)
                return FloatDesc;
            if (pin == HitMaskPin)
                return MaskDesc;
            if (pin == SourceIndicesPin)
                return IntDesc;
            return null;
        }

        public override unsafe bool OnProcedure(TtPgcGraph graph)
        {
            LastDiagnostic = null;
            var inputPoints = graph.ResolveInput(PointsPin) as TtSuperBuffer<Vector3, FFloat3Operator>;
            try
            {
                var projectedPoints = graph.BufferCache.FindBuffer(ProjectedPointsPin);
                var normals = graph.BufferCache.FindBuffer(NormalsPin);
                var hitDistances = graph.BufferCache.FindBuffer(HitDistancesPin);
                var hitMask = graph.BufferCache.FindBuffer(HitMaskPin);
                var sourceIndices = graph.BufferCache.FindBuffer(SourceIndicesPin);
                projectedPoints?.ResizePixels();
                normals?.ResizePixels();
                hitDistances?.ResizePixels();
                hitMask?.ResizePixels();
                sourceIndices?.ResizePixels();

                if (inputPoints == null)
                    return Fail(graph, "Points input is required");
                var context = graph.ExecutionContext;
                var world = context?.World;
                if (world?.CollideOctree?.mOctree == null)
                    return Fail(graph, "Surface Projection requires a runtime world collision octree");

                var direction = Direction;
                if (!NormalizeFinite(ref direction))
                    return Fail(graph, "Direction must be a finite non-zero vector");
                float maxDistance = MaxDistance;
                if (!float.IsFinite(maxDistance) || maxDistance <= 0.0f)
                    return Fail(graph, "MaxDistance must be a finite value greater than zero");
                float startOffset = StartOffset;
                if (!float.IsFinite(startOffset) || startOffset < 0.0f)
                    return Fail(graph, "StartOffset must be a finite non-negative value");

                var directionD = direction.AsDVector();
                double rayLength = maxDistance + startOffset;
                var candidates = new List<TtNode>();
                int count = GetElementCount(inputPoints);
                int hitCount = 0;
                for (int i = 0; i < count; i++)
                {
                    var point = GetLinearPixel<Vector3>(inputPoints, i);
                    var pointD = point.AsDVector();
                    var start = pointD - directionD * startOffset;
                    var end = pointD + directionD * maxDistance;
                    if (TryProject(context, in start, in end, in direction, rayLength,
                        candidates, out var projectedPoint, out var normal, out var distance))
                    {
                        AddResult(projectedPoints, normals, hitDistances, hitMask, sourceIndices,
                            in projectedPoint, in normal, distance, true, i);
                        hitCount++;
                    }
                    else if (MissPolicy == ESurfaceProjectionMissPolicy.KeepOriginal)
                    {
                        var missNormal = Vector3.Zero;
                        AddResult(projectedPoints, normals, hitDistances, hitMask, sourceIndices,
                            in point, in missNormal, -1.0f, false, i);
                    }
                }

                if (hitCount == 0 && count > 0)
                {
                    LastDiagnostic = "No input points hit a collidable scene surface";
                    context.AddDiagnostic($"Surface Projection '{Name}': {LastDiagnostic}");
                }
                return true;
            }
            finally
            {
                graph.ReleaseInput(PointsPin);
            }
        }

        bool TryProject(TtPgcExecutionContext context, in DVector3 start, in DVector3 end,
            in Vector3 direction, double rayLength, List<TtNode> candidates,
            out Vector3 projectedPoint, out Vector3 normal, out float distance)
        {
            projectedPoint = Vector3.Zero;
            normal = Vector3.Zero;
            distance = -1.0f;

            candidates.Clear();
            var ray = new DRay
            {
                Position = start,
                Direction = direction,
            };
            context.World.CollideOctree.GetColliding(candidates, in ray, rayLength);

            bool hasHit = false;
            double closestDistanceSquared = double.MaxValue;
            VHitResult closestResult = new VHitResult();
            for (int i = 0; i < candidates.Count; i++)
            {
                var candidate = candidates[i];
                if (candidate == null || candidate.Placement == null ||
                    ReferenceEquals(candidate, context.HostVolume) ||
                    (IgnoreGeneratedNodes && context.HostVolume?.IsGeneratedNode(candidate) == true))
                    continue;

                var result = new VHitResult();
                if (!candidate.LineCheck(in start, in end, ref result))
                    continue;
                double distanceSquared = (result.Position - start).LengthSquared();
                if (distanceSquared >= closestDistanceSquared)
                    continue;
                closestDistanceSquared = distanceSquared;
                closestResult = result;
                hasHit = true;
            }

            if (!hasHit)
                return false;
            projectedPoint = closestResult.Position.ToSingleVector3();
            normal = closestResult.Normal;
            if (!NormalizeFinite(ref normal))
                normal = -direction;
            distance = (float)Math.Sqrt(closestDistanceSquared);
            return true;
        }

        static unsafe void AddResult(TtBufferComponent points, TtBufferComponent normals,
            TtBufferComponent distances, TtBufferComponent hitMask, TtBufferComponent sourceIndices,
            in Vector3 point, in Vector3 normal, float distance, bool hasHit, int sourceIndex)
        {
            points?.AddPixel(in point);
            normals?.AddPixel(in normal);
            distances?.AddPixel(in distance);
            sbyte mask = hasHit ? (sbyte)1 : (sbyte)0;
            hitMask?.AddPixel(in mask);
            sourceIndices?.AddPixel(in sourceIndex);
        }

        bool Fail(TtPgcGraph graph, string message)
        {
            LastDiagnostic = message;
            graph.ExecutionContext?.AddDiagnostic($"Surface Projection '{Name}': {message}");
            Profiler.Log.WriteLine<Profiler.TtPgcGategory>(Profiler.ELogTag.Warning,
                $"Surface Projection '{Name}': {message}");
            return false;
        }

        static int GetElementCount(TtBufferComponent buffer)
        {
            if (buffer == null)
                return 0;
            long count = (long)buffer.Width * buffer.Height * buffer.Depth;
            return count > int.MaxValue ? int.MaxValue : (int)count;
        }

        static T GetLinearPixel<T>(TtBufferComponent buffer, int index) where T : unmanaged
        {
            int width = Math.Max(1, buffer.Width);
            int height = Math.Max(1, buffer.Height);
            int x = index % width;
            int y = (index / width) % height;
            int z = index / (width * height);
            return buffer.GetPixel<T>(x, y, z);
        }

        static bool NormalizeFinite(ref Vector3 value)
        {
            float length = value.Normalize();
            return length > 1e-6f && float.IsFinite(value.X) &&
                float.IsFinite(value.Y) && float.IsFinite(value.Z);
        }
    }
}
